cedar/urls.py
"""cedar URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/

"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.decorators import login_required

from djcelery.views import is_task_successful, task_status

from . import views
from cedar.forms import CedarPasswordResetForm

from heritage.forms import HeritageAssetForm

urlpatterns = [
    url(r'^$', login_required(views.HomeView.as_view()), name='home'),
    url(r'^spatialtools/', include('geoinfo.urls', namespace='geoinfo')),

    url(r'^heritage/', include('heritage.urls', namespace='heritage')),
    url(r'^heritage/', include('library.urls', namespace='heritage-library', app_name='library'),
        {
            'default_asset_model': 'heritage.heritageasset',
            'default_asset_modelform': HeritageAssetForm}
        ),

    url(r'^development/', include('development.urls', namespace='development')),
    # url(r'^development/', include('library.urls', namespace='development-library', app_name='library')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^assets/', include('assets.urls', namespace='assets')),
    url(r'^help/', include('help.urls', namespace='help')),
    url(r'^communication/', include('communication.urls', namespace='communication')),
    url(r'^eco/', include('ecosystems.urls', namespace='ecosystems')),

    # url(r'^secure/(?P<file_id>[0-9]+)', login_required(assets.views.download_private_file), name='secure'),
    # url(r'^{0}/(?P<file_id>[0-9]+)'.format(settings.SECURE_MEDIA_URL.lstrip('/')), login_required(assets.views.download_private_file), name='secure_handler'),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

    url(r'^crm/', include('crm.urls', namespace="crm")),
    url(r'^maps/', include('maps.urls', namespace="maps")),
    url(r'^communitymap/', include('communitymap.urls', namespace="communitymap")),

    # AUTH and USER SETTINGS:
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': settings.LOGIN_URL}, name='logout'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(
        r'^password/reset/$',
        'django.contrib.auth.views.password_reset',
        name='password_reset',
        kwargs={
            'template_name': 'password_reset_form.html',
            'email_template_name': 'password_reset.txt',
            'html_email_template_name': 'password_reset_email.html',
            'subject_template_name': 'password_reset_subject.txt',
            'password_reset_form': CedarPasswordResetForm
        }
    ),
    url(
        r'^password/reset/done/$',
        'django.contrib.auth.views.password_reset_done',
        name='password_reset_done',
        kwargs={
            'template_name': 'password_reset_done.html'
        }
    ),
    url(
        r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm',
        kwargs={
            'template_name': 'password_reset_confirm.html',
            'post_reset_redirect': 'password_reset_complete'
        }
    ),
    url(
        r'^password/reset/complete/$',
        'django.contrib.auth.views.password_reset_complete',
        name='password_reset_complete',
        kwargs={
            'template_name': 'password_reset_complete.html',
        }
    ),
    url(r'^user-settings/$', login_required(views.UpdateUserSettingsView.as_view()), name='user-settings'),
    url(
        r'^user-settings/change-password$',
        'django.contrib.auth.views.password_change',
        name='change-password',
        kwargs={
            'template_name': 'user_password_change_form.html',
            'post_change_redirect': 'change-password-done',
        }
    ),
    url(
        r'^user-settings/change-password-done$',
        'django.contrib.auth.views.password_change_done',
        name='change-password-done',
        kwargs={'template_name': 'user_password_change_done.html'}
    ),

    # Search - this is the site-wide search. Heritage has it's own.
    # url(r'^search/', login_required(assets.views.SecureAssetSearchView.as_view()), name='search'),

    # Provide a way to access the 404 page outside of DEBUG mode.
    url(r'^404/', views.Cedar404View.as_view(), name='404'),
    # Provide a way to access the 403 page outside of DEBUG mode.
    url(r'^403/', views.Cedar403View.as_view(), name='403'),

    # Additionally, we include login URLs for the browsable API.
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Core celery views to expose webhooks.
    url(r'^celery/apply/(?P<task_name>.*)/$', views.apply_celery_task, name='celery-apply'),
    url(r'^celery/(?P<task_id>[\w\d\-]+)/done/?$', is_task_successful, name='celery-is_task_successful'),
    url(r'^celery/(?P<task_id>[\w\d\-]+)/status/?$', task_status, name='celery-task_status'),
    url(r'^celery/(?P<task_id>[\w\d\-]+)/revoke/?$', views.revoke_celery_task, name='celery-task_revoke'),

    # discussion top-level
    url(r'^comments/', include('django_comments.urls')),

    # Django taggit autosuggest top-level
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^tags/', include('tags.urls', namespace='tags'))
]

# Rename Admin header here:
admin.site.site_header = 'Cedar 8 Administration'

crm/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'role', views.RoleViewSet, 'role')
router.register(r'organization', views.OrganizationViewSet, 'organization')
router.register(r'person', views.PersonViewSet, 'person')

urlpatterns = [
    url(r'^person/list/$', views.PersonListView.as_view(), name='person-list'),
    url(r'^person/(?P<pk>[0-9]+)/$', views.PersonDetailView.as_view(), name='person-detail'),
    url(r'^person/new/$', views.PersonCreateView.as_view(), name='person-create'),
    url(r'^person/(?P<pk>[0-9]+)/update/$', views.PersonUpdateView.as_view(), name='person-update'),
    url(r'^person/(?P<pk>[0-9]+)/delete/$', views.PersonDeleteView.as_view(), name='person-delete'),

    url(r'^organization/list/$', views.OrganizationListView.as_view(), name='organization-list'),
    url(r'^organization/(?P<pk>[0-9]+)/$', views.OrganizationDetailView.as_view(), name='organization-detail'),
    url(r'^organization/(?P<pk>[0-9]+)/update/$', views.OrganizationUpdateView.as_view(), name='organization-update'),
    url(r'^organization/(?P<pk>[0-9]+)/delete/$', views.OrganizationDeleteView.as_view(), name='organization-delete'),
    url(r'^organization/new/$', views.OrganizationCreateView.as_view(), name='organization-create'),

    # Rest API URL routing.
    url(r'^api/', include(router.urls, namespace='api')),
]

geoinfo/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'layer', views.GISLayerViewSet, 'layer')
router.register(r'feature', views.GISFeatureViewSet, 'feature')
router.register(r'spatialreport', views.SpatialReportViewSet, 'spatialreport')

urlpatterns = [
    url(r'^$', views.DashboardView.as_view(), name='dashboard'),

    # Layer views
    url(r'^layer/misc/(list/)?$', views.GISLayerListView.as_view(), name='layer-list'),
    url(r'^layer/all/(list/)?$', views.GISLayerMasterListView.as_view(), name='layer-master-list'),
    url(r'^layer/(?P<pk>[0-9]+)/$', views.GISLayerDetailView.as_view(), name='layer-detail'),
    url(r'^feature/(?P<pk>[0-9]+)/$', views.GISFeatureDetailView.as_view(), name='feature-detail'),
    url(r'^layer/new/', views.GISLayerCreateView.as_view(), name='layer-create'),
    url(r'^layer/(?P<pk>[0-9]+)/update/$', views.GISLayerUpdateView.as_view(), name='layer-update'),
    url(r'^layer/(?P<pk>[0-9]+)/delete/$', views.GISLayerDeleteView.as_view(), name='layer-delete'),

    # Spatial report views
    url(r'^spatialreport/(list/)?$', views.SpatialReportListView.as_view(), name='spatialreport-list'),
    url(r'^spatialreport/(?P<pk>[0-9]+)/$', views.SpatialReportDetailView.as_view(), name='spatialreport-detail'),
    url(r'^spatialreport/new/$', views.SpatialReportCreateView.as_view(), name='spatialreport-create'),
    url(r'^spatialreport/(?P<pk>[0-9]+)/update/$',
        views.SpatialReportUpdateView.as_view(), name='spatialreport-update'),
    url(r'^spatialreport/(?P<pk>[0-9]+)/delete/$',
        views.SpatialReportDeleteView.as_view(), name='spatialreport-delete'),

    # Spatial report item views
    url(r'^spatialreport/(?P<report_pk>[0-9]+)/item/new/$',
        views.SpatialReportItemCreateView.as_view(), name='spatialreportitem-create'),
    url(r'^spatialreport/(?P<report_pk>[0-9]+)/item/(?P<pk>[0-9]+)/update/$',
        views.SpatialReportItemUpdateView.as_view(), name='spatialreportitem-update'),
    url(r'^spatialreportitem/(?P<pk>[0-9]+)/delete/$',
        views.SpatialReportItemDeleteView.as_view(), name='spatialreportitem-delete'),

    # Rest API URL routing.
    url(r'^api/', include(router.urls, namespace='api')),
    url(r'^api/layer-master/$', views.GISLayerMasterListAPIView.as_view(), name='layer-master-list-api'),
    url(r'^api/feature-point/$', views.GISFeaturePointViewSet.as_view(), name='feature-point-list'),
    url(r'^api/feature-line/$', views.GISFeatureLineViewSet.as_view(), name='feature-line-list'),
    url(r'^api/feature-polygon/$', views.GISFeaturePolygonViewSet.as_view(), name='feature-polygon-list'),
]

cedar/models.py
from django.db import models
from cedar.managers import PrefixedIDManager


class PrefixedIDModelAbstract(models.Model):
    """
    Add this mixin and you only need to override the get_prefix() method.
    get_prefix() should return something like:
        - "I-" or "CB-"
        
    This model abstract comes along with the Prefixed ID model manager that automatically annotates
    querysets with the prefixed_id
    """

    objects = PrefixedIDManager()

    @classmethod
    def get_prefix(cls):
        """
        Needs to be a classmethod so that it's accessible from the manager.
        should return a prefix like:
            "I-" or "CB-"
        :return: 
        """
        return ""

    @property
    def prefixed_id(self):
        return self.get_prefix() + str(self.id)

    class Meta:
        abstract = True

cedar/views.py
from __future__ import absolute_import
import csv
from anyjson import serialize as json_serialize

from django.views.generic import TemplateView, UpdateView, FormView

from django.core.urlresolvers import reverse
from django.utils.decorators import method_decorator

from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.http import Http404, HttpResponse

from cedar.celery import app as celery_app
from celery.five import items

from .forms import UserSettingsForm, UserSettingsFormset

from help.mixins import HelpContextMixin

import celery.task  # noqa


class HomeView(TemplateView):
    template_name = 'home.html'


class UpdateUserSettingsView(HelpContextMixin, UpdateView):
    template_name = 'cedar/user-settings-form.html'
    form_class = UserSettingsForm
    model = User
    page_help_name = 'cedar:user-settings-update'

    def get_context_data(self, **kwargs):
        context = super(UpdateUserSettingsView, self).get_context_data(**kwargs)
        if self.request.POST:
            crm_person_formset = UserSettingsFormset(self.request.POST, self.request.FILES, instance=self.request.user)
            context['crm_person_formset'] = crm_person_formset

        else:
            context['crm_person_formset'] = UserSettingsFormset(instance=self.request.user)

        return context

    def form_valid(self, form):
        # Check the inline user settings formset:
        user_settings_formset = UserSettingsFormset(self.request.POST, self.request.FILES, instance=form.instance)
        if user_settings_formset.is_valid():
            user_settings_formset.save()
            return super(UpdateUserSettingsView, self).form_valid(form)
        else:
            return super(UpdateUserSettingsView, self).form_invalid(form)

    # Overriding get object here lets us call up the view without
    # providing a PK because we use the request.user object instead.
    def get_object(self, queryset=None):
        return self.request.user

        # def get_form(self, form_class=None):
        #     return self.form_class(user=self.request.user)
        #

    def get_success_url(self):
        return reverse('user-settings')


class UserPasswordUpdateView(FormView):
    form_class = PasswordChangeForm
    # success_url = reverse('profile_view_details')
    template_name = 'registration/password_change_form.html'

    def get_form_kwargs(self):
        kwargs = super(UserPasswordUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        # messages.add_message(self.request, messages.INFO, _('profile changed'))
        return super(UserPasswordUpdateView, self).form_valid(form)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UserPasswordUpdateView, self).dispatch(*args, **kwargs)


class Cedar404View(TemplateView):
    template_name = '404.html'


class Cedar403View(TemplateView):
    template_name = '403.html'


def JsonResponse(response):
    return HttpResponse(json_serialize(response), content_type='application/json')


# Need to overwrite the view from djcelery because pip installs with python2 things for some reason...
def celery_task_view(task):
    """
    Decorator turning any task into a view that applies the task
    asynchronously. Keyword arguments (via URLconf, etc.) will
    supercede GET or POST parameters when there are conflicts.
    Returns a JSON dictionary containing the keys ``ok``, and
        ``task_id``.
    """

    def _applier(request, **options):
        kwargs = request.POST if request.method == 'POST' else request.GET
        # no multivalue
        kwargs = {k: v for k, v in items(kwargs)}
        if options:
            kwargs.update(options)
        result = task.apply_async(kwargs=kwargs)
        return JsonResponse({'ok': 'true', 'task_id': result.task_id})

    return _applier


@login_required()
def apply_celery_task(request, task_name):
    """
    View applying a task.
    **Note:** Please use this with caution. Preferably you shouldn't make this
        publicly accessible without ensuring your code is safe!
    """
    tasks = celery_app.tasks
    print(tasks.keys())
    try:
        task = tasks[task_name]
    except KeyError:
        raise Http404('apply: no such task')

    # Later on we can add code here to make sure the tasks applied are in a white-list.

    return celery_task_view(task)(request)


def revoke_celery_task(request, task_id):
    task = celery_app.AsyncResult(task_id)
    task.revoke(terminate=True)
    return JsonResponse({'terminated': 'true', 'task_id': task_id})

cedar/templates/base.html
{% load staticfiles %}
{% load cedar_extras %}
{% load repeatedblocks %}
{% load help %}
{% load cedar_settings %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <link rel="shortcut icon" type="image/png" href="{% static 'css/cedarbox_icon_gry.png' %}"/>

    {#    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">#}
    <link href="{% static 'css/cedar-material-icons.css' %}" rel="stylesheet"/>
    <link href="{% static 'lib/materialize-src/css/materialize.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/cedar.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/task-mon.css' %}" rel="stylesheet"/> {# task-mon for the global Harvest Mail button #}
    <script src="{% static 'js/history.js' %}"></script>
    <script src="{% static 'build/cedar/js/cedar.js' %}"></script>

    {% block stylesheets %}{% endblock %}

{#    If jquery is included here then child templates can import their own#}
{#    js with their own document ready functions#}
    <script src="{% static 'lib/jquery/jquery-1.11.3.js' %}"></script>
    <script src="{% static 'lib/jquery-expander/jquery.expander.min.js' %}"></script>

</head>
<body>

{% block nav %}
    {% include 'sidenav.html' %}
{% endblock %}
<main>
    {% block content %}
        {% spinner %}
        {% block second_bar %}
            <div class="row grey lighten-4">
{#            <div class="valign-wrapper hide-on-med-and-down">#}
            {# JS is sometimes used to make the print pages look correct even when not printing.  We don't want to hide this unless its a real print page. #}
            <div class="hide-on-med-and-down top-bar-hide-on-print">
                    <div class="second_bar_page_title_outer">
                        <div class="row grey lighten-4">
                            <div class="col s6 second_bar_page_title grey-text text-darken-2">
                                <h4>{% repeated_block second_bar_page_title %}{% endblock %}</h4>
                            </div>
                            <div class="col s6 second_bar_secondary_content_right">
                                <div class="grey-text text-darken-1">
        {% repeated_block second_bar_secondary_content_right %}{% endblock %}
    {% include 'cedar/edit_buttons.html' %}
    {% help_button %}
                                </div>
                            </div>
                        </div>
                        <div class="row grey lighten-4">
                            <div class="col s12 second_bar_secondary_title grey-text text-lighten">
                                <h5>{% repeated_block second_bar_secondary_title %}{% endblock %}</h5>
                            </div>
                        </div>
                    </div>
                {#    <div class="col s12 m5 l4">#}

                </div>

    {# This is this is the top bar that shows on mobile.  It also shows on print. #}
                <div class="show-on-medium-and-down hide-on-large-only">
                    <div class="row">
                        <div class="col s12">
                            <div class="grey-text text-darken-2 left"><h5>{% repeat second_bar_page_title %}</h5></div>
                            <div class="grey-text text-lighten right"><h5>{% repeat second_bar_secondary_title %}</h5></div>
                        </div>
                        <div class="col s12">
                            <div class="grey-text text-darken-1 right">
                                {% repeat second_bar_secondary_content_right %}
                                <span class="hide-on-print">
                                    {% include 'cedar/edit_buttons.html' %}
                                    {% help_button %}
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endblock second_bar %}
    {% endblock content %}

    {#  insert super secret help modal div area #}
    {% help_modal %}
    {% include 'cedar/user-menu-modals.html' %}

</main>



<script src="{% static 'lib/materialize-src/js/bin/materialize.min.js' %}"></script>
<script src="{% static 'js/task-mon.js' %}"></script> {# task-mon for the global Harvest Mail button #}
<script>
    $(document).ready(function () {
        $("#id_password").click();  // This is a workout for
                                    // autofill password text
                                    // overlapping with css text.


        $('.second_bar_secondary_content_right').pushpin({
            top: 50,
            offset: 0
        });

        $('form').on('submit', function (e) {
            $('.progress').css('visibility', 'visible');
        });

    });

    window.chip_hack();

    {% get_background_url as bg_url %}
    var bg_img_url = "{{ bg_url|safe }}";
    $('#background-image').css('background-image', 'url("' + bg_img_url + '")');
</script>
{% block messages %}
    {% messages %}
{% endblock messages %}
{% block javascripts %}{% endblock %}
</body>
</html>

cedar/templates/detail.html
{% extends 'base.html' %}
{% block content %}
    {{ block.super }}
    <div class="row">
        <div class="row">
            <div class="progress">
                <div class="indeterminate"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            {% block detail-content %}{% endblock %}
        </div>
    </div>
{% endblock %}

cedar/templates/home.html
{% extends 'base.html' %}
{% block title %}Cedar{% endblock %}
{% block stylesheets %}
    {#    {{ block.super }}#}
    <style>
        /* Override the padding for the nav side bar: */
        header, main, footer {
            padding-left: 50px;
            padding-right: 50px;
        }
    </style>
{% endblock %}


{% block content %}
    <div id="background-image">
        <div style="height:200px;"></div>
    </div>

    {% block nav %}{# just blanking out the side nav #}{% endblock %}

    <div class="splash-page-top-space"></div>
    <div class="row">
        {#        <div class="home-center valign-wrapper center-align card-panel">#}
        <div class="home-center card-panel">
            <div class="row">
                <div class="col l4 m6 s12">
                    <div class="center card small hoverable home-card heritage">
                        <a href="{% url "heritage:dashboard" %}">
                            <i class="material-icons home-icon">local_library</i>
                            <p class="promo-caption">Heritage</p>
                            <p class="light center">Curate cultural data from Traditional Ecological Knowledge,
                                Traditional Use Studies, and Archaeology Reports</p>
                        </a>
                    </div>
                </div>
                <div class="col l4 m6 s12">
                    <div class="center card small hoverable home-card development">
                        <a href="{% url "development:dashboard" %}">
                            <i class="material-icons home-icon">assignment</i>
                            <p class="promo-caption">Development</p>
                            <p class="light center">Manage consultation and run spatial analysis on development activities</p>
                        </a>
                    </div>
                </div>
                <div class="col l4 offset-m3 m6 s12">
                    <div class="center card small hoverable home-card ecosystems">
                        <a href="{% url "ecosystems:dashboard" %}">
                            <i class="material-icons home-icon">nature_people</i>
                            <p class="promo-caption">Ecosystems</p>
                            <p class="light center">
                                Manage ecosystems reports and GIS layers. Explore your ecosystems library.
                            </p>
                        </a>
                    </div>
                </div>
{#                <div class="col l3 m6 s12">#}
{#                    <div class="center card small hoverable home-card nation-admin">#}
{#                        <span >#}
{#                            <i class="material-icons home-icon">account_balance</i>#}
{#                            <p class="promo-caption">Nation Administration</p>#}
{#                        </span>#}
{#                        <p class="light center">#}
{#                            Manage council meetings, create agendas, minutes, and resolutions.#}
{#                        </p>#}
{#                    </div>#}
{#                    <div class="coming-soon">Coming Soon</div>#}
{#                </div>#}
            </div>
            <div class="row center">
                <div class="col offset-l2 offset-m2 l2 m4 s6">
                    <div class="center card small hoverable home-card-sub">
                        <i class="material-icons home-icon">supervisor_account</i>
                        <p class="promo-caption">Contacts</p>
                        <p class="light center">Manage organization and contact information</p>
                    </div>
                </div>
                <div class="col l2 m4 s6">
                    <div class="center card small hoverable home-card-sub">
                        <i class="material-icons home-icon">forum</i>
                        <p class="promo-caption">Communications</p>
                        <p class="light center">Track phone calls, faxes, letters. Automated
                            tools pin emails to related projects.
                        </p>
                    </div>
                </div>
{#                <div class="col l2 m4 s6">#}
{#                    <div class="center card small hoverable home-card-sub">#}
{#                        <i class="material-icons home-icon">people_outline</i>#}
{#                        <p class="promo-caption">Meetings</p>#}
{#                        <p class="light center">Record information on meetings within any App</p>#}
{#                    </div>#}
{#                    <div class="coming-soon">Coming Soon</div>#}
{#                </div>#}
                <div class="row hide-on-large-only hide-on-small-only"></div>
                <div class="col l2 m4 offset-m2 s6">
                    <div class="center card small hoverable home-card-sub">
                        <i class="material-icons home-icon">public</i>
                        <p class="promo-caption">Spatial</p>
                        <p class="light center">Access and manage spatial data. Create and run detailed reports.
                            Explore interactive maps.
                        </p>
                    </div>
                </div>
                <div class="col l2 m4 s6">
                    <div class="center card small hoverable home-card-sub">
                        <i class="material-icons home-icon">library_books</i>
                        <p class="promo-caption">Library</p>
                        <p class="light center">Manage organization and contact information</p>
                    </div>
                </div>
{#                <div class="col l2 m4 s6">#}
{#                    <div class="center card small hoverable home-card-sub">#}
{#                        <i class="material-icons home-icon">tap_and_play</i>#}
{#                        <p class="promo-caption">Mobile</p>#}
{#                        <p class="light center">Collect survey forms and multimedia data in the field and#}
{#                            sync data with Cedar Apps.#}
{#                        </p>#}
{#                    </div>#}
{#                    <div class="coming-soon">Coming Soon</div>#}
{#                </div>#}
            </div>
        </div>
    </div>

{% endblock %}

{#{% block footer %}#}
{#    <div class="footer-copyright">#}
{#        <div class="container">#}
{#        Copyright © Geomemes Research Inc.#}
{#        <a class="grey-text text-lighten-4 right" href="#!">More Links</a>#}
{#        </div>#}
{#    </div>#}
{#{% endblock %}#}

cedar/templates/sidenav.html
{% load staticfiles %}
{% load cedar_extras %}

<nav class="blue darken-1" role="navigation">
    <div class="nav-wrapper">
        <div class="blue darken-1">
            <a href="{% url 'home' %}" class="brand-logo hide-on-large-only" >
                <div class="valign-wrapper">
                    <img src="{% static 'css/cedarbox_icon_wht.png' %}" id="cedarbox-icon-white">&nbsp;&nbsp;<strong>CedarBox</strong>
                </div>
            </a>
            <div class="hide-on-large-only">{% user_menu user_menu_id="med_small_screen" %}</div>
            <a id="sidenav-collapse-btn" href="#" data-activates="mobile-nav" class="button-collapse"><i class="material-icons">menu</i></a>
            <ul class="side-nav fixed blue darken-1 grey-text text-lighten-2 " id="mobile-nav">
                <li>
                    <a href="{% url 'home' %}" class="hide-on-med-and-down">
                        <div class="valign-wrapper">
                            <img src="{% static 'css/cedarbox_icon_wht.png' %}" id="cedarbox-icon-white" />&nbsp;&nbsp;
                            <span class="grey-text text-lighten-5">
                                <h5>CedarBox</h5>
                            </span>
                        </div>
                    </a>
                </li>
                <ul class="collapsible" data-collapsible="expandable">

                    {% include 'crm/sidenav.html' %}
                    {% include 'heritage/sidenav.html' %}
                    {% include 'development/sidenav.html' %}
                    {% include 'ecosystems/sidenav.html' %}
                    {% include 'geoinfo/sidenav.html' %}
                </ul>
                {% if not user.is_authenticated %}
                    <li><a class="grey-text text-lighten-2" href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
        <div class="row hide-on-med-and-down">
            <div class="col s10 offset-s2 m6 offset-m6 l4 offset-l8">
                {% user_menu user_menu_id="large_screen" %}
            </div>
        </div>
    </div>

</nav>


{% block nav-js %}
<script>
    {% comment %}
        Override this url in a template if you are accessing a url that doesn't
        map well to a nav link (eg Person Details should map to "People"

        UPDATE:
            while some templates still override this url in template javascript,
            it is preferable to start using the NavMixin class and setting
            the nav url in the class itself.

    {% endcomment %}
    {%  if not nav_url %}
        var current_nav_url = '{{ request.path|safe }}';
    {% else %}
        var current_nav_url = '{{ nav_url|safe }}';
    {% endif %}
</script>
    <script type="text/javascript" src="{% static 'js/sidenav.js' %}"></script>
{% endblock %}