cedar/urls.py
"""cedar URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/

"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.decorators import login_required

from djcelery.views import is_task_successful, task_status

from . import views
from cedar.forms import CedarPasswordResetForm

from heritage.forms import HeritageAssetForm

urlpatterns = [
    url(r'^$', login_required(views.HomeView.as_view()), name='home'),
    url(r'^spatialtools/', include('geoinfo.urls', namespace='geoinfo')),

    url(r'^heritage/', include('heritage.urls', namespace='heritage')),
    url(r'^heritage/', include('library.urls', namespace='heritage-library', app_name='library'),
        {
            'default_asset_model': 'heritage.heritageasset',
            'default_asset_modelform': HeritageAssetForm}
        ),

    url(r'^development/', include('development.urls', namespace='development')),
    # url(r'^development/', include('library.urls', namespace='development-library', app_name='library')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^assets/', include('assets.urls', namespace='assets')),
    url(r'^help/', include('help.urls', namespace='help')),
    url(r'^communication/', include('communication.urls', namespace='communication')),
    url(r'^eco/', include('ecosystems.urls', namespace='ecosystems')),

    # url(r'^secure/(?P<file_id>[0-9]+)', login_required(assets.views.download_private_file), name='secure'),
    # url(r'^{0}/(?P<file_id>[0-9]+)'.format(settings.SECURE_MEDIA_URL.lstrip('/')), login_required(assets.views.download_private_file), name='secure_handler'),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

    url(r'^crm/', include('crm.urls', namespace="crm")),
    url(r'^maps/', include('maps.urls', namespace="maps")),
    url(r'^communitymap/', include('communitymap.urls', namespace="communitymap")),

    # AUTH and USER SETTINGS:
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': settings.LOGIN_URL}, name='logout'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(
        r'^password/reset/$',
        'django.contrib.auth.views.password_reset',
        name='password_reset',
        kwargs={
            'template_name': 'password_reset_form.html',
            'email_template_name': 'password_reset.txt',
            'html_email_template_name': 'password_reset_email.html',
            'subject_template_name': 'password_reset_subject.txt',
            'password_reset_form': CedarPasswordResetForm
        }
    ),
    url(
        r'^password/reset/done/$',
        'django.contrib.auth.views.password_reset_done',
        name='password_reset_done',
        kwargs={
            'template_name': 'password_reset_done.html'
        }
    ),
    url(
        r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm',
        kwargs={
            'template_name': 'password_reset_confirm.html',
            'post_reset_redirect': 'password_reset_complete'
        }
    ),
    url(
        r'^password/reset/complete/$',
        'django.contrib.auth.views.password_reset_complete',
        name='password_reset_complete',
        kwargs={
            'template_name': 'password_reset_complete.html',
        }
    ),
    url(r'^user-settings/$', login_required(views.UpdateUserSettingsView.as_view()), name='user-settings'),
    url(
        r'^user-settings/change-password$',
        'django.contrib.auth.views.password_change',
        name='change-password',
        kwargs={
            'template_name': 'user_password_change_form.html',
            'post_change_redirect': 'change-password-done',
        }
    ),
    url(
        r'^user-settings/change-password-done$',
        'django.contrib.auth.views.password_change_done',
        name='change-password-done',
        kwargs={'template_name': 'user_password_change_done.html'}
    ),

    # Search - this is the site-wide search. Heritage has it's own.
    # url(r'^search/', login_required(assets.views.SecureAssetSearchView.as_view()), name='search'),

    # Provide a way to access the 404 page outside of DEBUG mode.
    url(r'^404/', views.Cedar404View.as_view(), name='404'),
    # Provide a way to access the 403 page outside of DEBUG mode.
    url(r'^403/', views.Cedar403View.as_view(), name='403'),

    # Additionally, we include login URLs for the browsable API.
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Core celery views to expose webhooks.
    url(r'^celery/apply/(?P<task_name>.*)/$', views.apply_celery_task, name='celery-apply'),
    url(r'^celery/(?P<task_id>[\w\d\-]+)/done/?$', is_task_successful, name='celery-is_task_successful'),
    url(r'^celery/(?P<task_id>[\w\d\-]+)/status/?$', task_status, name='celery-task_status'),
    url(r'^celery/(?P<task_id>[\w\d\-]+)/revoke/?$', views.revoke_celery_task, name='celery-task_revoke'),

    # discussion top-level
    url(r'^comments/', include('django_comments.urls')),

    # Django taggit autosuggest top-level
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^tags/', include('tags.urls', namespace='tags'))
]

# Rename Admin header here:
admin.site.site_header = 'Cedar 8 Administration'

crm/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'role', views.RoleViewSet, 'role')
router.register(r'organization', views.OrganizationViewSet, 'organization')
router.register(r'person', views.PersonViewSet, 'person')

urlpatterns = [
    url(r'^person/list/$', views.PersonListView.as_view(), name='person-list'),
    url(r'^person/(?P<pk>[0-9]+)/$', views.PersonDetailView.as_view(), name='person-detail'),
    url(r'^person/new/$', views.PersonCreateView.as_view(), name='person-create'),
    url(r'^person/(?P<pk>[0-9]+)/update/$', views.PersonUpdateView.as_view(), name='person-update'),
    url(r'^person/(?P<pk>[0-9]+)/delete/$', views.PersonDeleteView.as_view(), name='person-delete'),

    url(r'^organization/list/$', views.OrganizationListView.as_view(), name='organization-list'),
    url(r'^organization/(?P<pk>[0-9]+)/$', views.OrganizationDetailView.as_view(), name='organization-detail'),
    url(r'^organization/(?P<pk>[0-9]+)/update/$', views.OrganizationUpdateView.as_view(), name='organization-update'),
    url(r'^organization/(?P<pk>[0-9]+)/delete/$', views.OrganizationDeleteView.as_view(), name='organization-delete'),
    url(r'^organization/new/$', views.OrganizationCreateView.as_view(), name='organization-create'),

    # Rest API URL routing.
    url(r'^api/', include(router.urls, namespace='api')),
]

ecosystems/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from ecosystems.views import DashboardView, SecureAssetsDashboardView, SecureAssetListView,\
    SecureAssetSearchView, SecureAssetSearchViewCSV, EcosystemsAssetDetailView, EcosystemsAssetCreateView,\
    EcosystemsAssetUpdateView, EcosystemsAssetDeleteView, EcosystemsGISLayerCreateView, EcosystemsGISLayerDeleteView, EcosystemsGISLayerDetailView,\
    EcosystemsGISLayerUpdateView, EcosystemsGISLayerListView, EcosystemsGISLayerViewSet, EcosystemsAssetViewSet, \
    EcosystemsGISLayerMasterListAPIView, EcosystemsProjectViewSet, EcosystemsGISLayerFeatureViewSet, PlantTagListView, PlantTagViewSet, \
    PlantTagDetailView, PlantTagCreateView, PlantTagUpdateView, PlantTagDeleteView, \
    AnimalTagViewSet, AnimalTagListView, AnimalTagDetailView, AnimalTagUpdateView, AnimalTagCreateView, AnimalTagDeleteView, \
    list_plant_or_animal_tags

import ecosystems

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'gislayers', EcosystemsGISLayerViewSet, 'gislayers')
router.register(r'assets', EcosystemsAssetViewSet, 'secure-assets')
router.register(r'project', EcosystemsProjectViewSet, 'project')
router.register(r'feature', EcosystemsGISLayerFeatureViewSet, 'feature')
router.register(r'plant', PlantTagViewSet, 'planttag')
router.register(r'animal', AnimalTagViewSet, 'animaltag')

urlpatterns = [
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'^settings/$', ecosystems.views.EcosystemsSettingsView.as_view(), name='settings'),

    url(r'^file/dashboard/$', SecureAssetsDashboardView.as_view(), name='secureasset-dashboard'),
    url(r'^file/list', SecureAssetListView.as_view(), name='secureasset-list'),
    url(r'^file/search/$', SecureAssetSearchView.as_view(), name='secureasset-search'),
    url(r'^file/search/csv/$', SecureAssetSearchViewCSV.as_view(), name='secureasset-search-csv'),

    url(r'^assets/(?P<pk>\d+)/$', EcosystemsAssetDetailView.as_view(), name='secureasset-detail'),
    url(r'^assets/new/$', EcosystemsAssetCreateView.as_view(), name='secureasset-create'),
    url(r'^assets/(?P<pk>\d+)/edit/$', EcosystemsAssetUpdateView.as_view(), name='secureasset-update'),
    url(r'^assets/(?P<pk>\d+)/delete/$', EcosystemsAssetDeleteView.as_view(), name='secureasset-delete'),

    url(r'^gislayer/new/$', EcosystemsGISLayerCreateView.as_view(), name='gislayer-create'),
    url(r'^gislayer/(?P<pk>\d+)/edit/$', EcosystemsGISLayerUpdateView.as_view(), name='gislayer-update'),
    url(r'^gislayer/(?P<pk>\d+)/delete/$', EcosystemsGISLayerDeleteView.as_view(), name='gislayer-delete'),
    url(r'^gislayer/list$', EcosystemsGISLayerListView.as_view(), name='gislayer-list'),
    url(r'^gislayer/(?P<pk>\d+)/$', EcosystemsGISLayerDetailView.as_view(), name='gislayer-detail'),

    # eco prjs:
    url(r'^project/(list/)?$', ecosystems.views.EcosystemsProjectListView.as_view(), name='project-list'),
    url(r'^project/(?P<pk>\d+)/$', ecosystems.views.EcosystemsProjectDetailView.as_view(), name='project-detail'),
    # url(r'^project/print/(?P<pk>\d+)/$', ecosystems.views.EcosystemsProjectDetailPrintView.as_view(), name='project-detail-print'),
    url(r'^project/new/$', ecosystems.views.EcosystemsProjectCreateView.as_view(), name='project-create'),
    url(r'^project/(?P<pk>\d+)/edit/$', ecosystems.views.EcosystemsProjectUpdateView.as_view(), name='project-update'),
    url(r'^project/(?P<pk>\d+)/delete/$', ecosystems.views.EcosystemsProjectDeleteView.as_view(), name='project-delete'),

    # eco prj locations (gis layers):
    url(r'^project/(?P<project_pk>\d+)/location/new/$', ecosystems.views.EcosystemsProjectGISLayerCreateView.as_view(),
        name='project-location-create'),
    url(r'^project/(?P<project_pk>\d+)/location/(?P<pk>\d+)/edit/$', ecosystems.views.EcosystemsProjectGISLayerUpdateView.as_view(),
        name='project-location-edit'),
    url(r'^project/(?P<project_pk>\d+)/location/(?P<pk>\d+)/delete/$', ecosystems.views.EcosystemsProjectGISLayerDeleteView.as_view(),
        name='project-location-delete'),

    # eco prj assets:
    url(r'^project/(?P<project_pk>\d+)/asset/(?P<pk>\d+)/$', ecosystems.views.EcosystemsProjectAssetDetailView.as_view(),
        name='project-secureasset-detail'),
    url(r'^project/(?P<project_pk>\d+)/asset/new/$', ecosystems.views.EcosystemsProjectAssetCreateView.as_view(), name='project-secureasset-create'),
    url(r'^project/print/(?P<pk>\d+)/$', ecosystems.views.EcosystemsProjectDetailPrintView.as_view(), name='project-detail-print'),
    url(r'^project/(?P<project_pk>\d+)/asset/(?P<pk>\d+)/edit/$', ecosystems.views.EcosystemsProjectAssetUpdateView.as_view(),
        name='project-secureasset-update'),
    url(r'^project/(?P<project_pk>\d+)/asset/(?P<pk>\d+)/delete/$', ecosystems.views.EcosystemsProjectAssetDeleteView.as_view(),
        name='project-secureasset-delete'),


    url(r'^plant/(list/)?$', PlantTagListView.as_view(), name='planttag-list'),
    url(r'^plant/new/$', PlantTagCreateView.as_view(), name='planttag-create'),
    url(r'^plant/(?P<pk>[0-9]+)/$', PlantTagDetailView.as_view(), name='planttag-detail'),
    url(r'^plant/(?P<pk>[0-9]+)/edit/$', PlantTagUpdateView.as_view(), name='planttag-update'),
    url(r'^plant/(?P<pk>\d+)/delete/$', PlantTagDeleteView.as_view(), name='planttag-delete'),
    
    url(r'^animal/(list/)?$', AnimalTagListView.as_view(), name='animaltag-list'),
    url(r'^animal/new/$', AnimalTagCreateView.as_view(), name='animaltag-create'),
    url(r'^animal/(?P<pk>[0-9]+)/$', AnimalTagDetailView.as_view(), name='animaltag-detail'),
    url(r'^animal/(?P<pk>[0-9]+)/edit/$', AnimalTagUpdateView.as_view(), name='animaltag-update'),
    url(r'^animal/(?P<pk>\d+)/delete/$', AnimalTagDeleteView.as_view(), name='animaltag-delete'),

    # Ajax search views for plant/animal autosuggestions
    url(r'^suggest_plant/$', list_plant_or_animal_tags, {'model_name': 'plant'}, name='plant-suggestions'),
    url(r'^suggest_animal/$', list_plant_or_animal_tags, {'model_name': 'animal'}, name='animal-suggestions'),

    # Wire up our API using automatic URL routing.
    url(r'^api/', include(router.urls, namespace='api')),
    url(r'^api/layer-master/$', EcosystemsGISLayerMasterListAPIView.as_view(), name='layer-master-list-api'),
]

ecosystems/templates/ecosystems/animaltag_confirm_delete.html
{% extends "base.html" %}
{% load cedar_material_form %}
{% load staticfiles %}
{% load cedar_extras %}

{# Uncomment the next line to blankout/override the 2nd bar #}
{#{% block second_bar %}{% endblock %}#}
{% block second_bar_page_title %}Delete Animal{% endblock %}
{% block second_bar_secondary_title %}{{ object.name }} {% endblock %}
{% block second_bar_secondary_content_right %}
    <a class="waves-effect waves-light btn grey lighten-5 grey-text text-darken-2"
       href="{% url 'ecosystems:animaltag-detail' object.pk %}">
        <div class="valign-wrapper">
            <i class="material-icons valign ">cancel</i>
            &nbsp;Cancel
        </div>
    </a>
{% endblock %}


{% block content %}
    {{ block.super }}
    <div class="section">
        <div class="row">
            <div class="col s12">
                <form action="{% url 'ecosystems:animaltag-delete'  object.pk %}" method="POST">
                    {% csrf_token %}
                    <p>
                        Are you sure you want to delete <strong>{{ object }}</strong>
                    </p>

                    <input class="waves-effect waves-light btn grey lighten-4 red-text text-darken-1" type="submit" value="Confirm delete"/>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    <script>
        var current_nav_url = '{% url "ecosystems:dashboard" %}';
    </script>

{% endblock %}

ecosystems/templates/ecosystems/ecosystemsasset_detail.html
{% extends 'assets/genericasset_detail.html' %}

ecosystems/templates/ecosystems/ecosystemsgislayer_form_fields.html
{% extends 'geoinfo/gislayer_form_fields.html' %}
{% load cedar_material_form %}
{% load staticfiles %}
{% load cedar_extras %}

{% block additional_form_fields_1 %}
    {{ form.project.as_hidden }}
{% endblock %}



{% block additional_form_fields_2 %}

{% endblock %}

ecosystems/templates/ecosystems/ecosystemsproject_detail.html
{% extends "base.html" %}
{#{% extends "cedar/table_narrow.html" %}#}

{% load staticfiles %}
{% load cedar_extras %}
{% load html_filters %}
{% load crm %}
{% load leaflet_assets %}
{% load ecosystems %}
{% load communication %}
{% load threadedcomments_tags %}
{% load discussion %}
{% load cedar_settings %}

{# Uncomment the next line to blankout/override the 2nd bar #}
{#{% block second_bar %}{% endblock %}#}
{% block second_bar_page_title %}
    Project Details
{% endblock %}
{% block second_bar_secondary_title %}
    {{ object.cedar_project_name }}
{% endblock %}
{% block second_bar_secondary_content_right %}
    <a class="waves-effect waves-light btn grey lighten-5 grey-text text-darken-2 {{ user|is_disabled:'ecosystems.change_ecosystemsproject' }}"
       href="{% url 'ecosystems:project-update' object.id %}">
        <div class="valign-wrapper">
            <i class="material-icons">mode_edit</i>
            &nbsp;Edit
        </div>
    </a>
    <a class="waves-effect waves-light btn grey lighten-5 grey-text text-darken-2 {{ user|is_disabled:'ecosystems.add_ecosystemsprojectasset' }}"
       href="{% url 'ecosystems:project-secureasset-create' object.id %}">
        <div class="valign-wrapper">
            <i class="material-icons">add_circle</i>
            &nbsp;File
        </div>
    </a>
    <a class="waves-effect waves-light btn grey lighten-5 grey-text text-darken-2"
       target="_blank"
       href="{% url 'ecosystems:project-detail-print' object.id %}">
        <div class="valign-wrapper">
            <i class="material-icons">print</i>
            &nbsp;Report
        </div>
    </a>
{% endblock %}

{% block stylesheets %}
    {{ block.super }}
    {% leaflet_assets_css %}
{% endblock %}

{% block content %}
    {{ block.super }}
    <div class="section">
        <div class="row">
            <div class="col s12 m3 l3 thin-border-right-grey">
                <div class="">
                    <strong>Project Code (Mail Harvest)</strong>
                    <p class=" grey-text">{{ object.cedar_project_code }}</p>
                </div>
                <div class="">
                    <strong>Filing Code</strong>
                    <p class=" grey-text">{{ object.filing_code|default_if_none:'' }}</p>
                </div>
                <div class="section">
                    <strong>Tags</strong>
                    {% for tag in object.tags.all %}
                    <div class="chip">
                        {{ tag }}
                        {# <i class="material-icons">close</i>#}
                    </div>
                    {% endfor %}
                </div>

            </div>
            <div class="col s12 m9 l9">
                <div>
                    <div>
                        <ul class="tabs hide-scroll-x">
                            <li class="tab col s3">
                                <a href="#tab-main"
                                   class="active tooltipped-project-details"
                                   data-tooltip="Details"
                                   data-position="top">
                                    <i class="material-icons" style="font-size:35px;">subject</i>
                                </a>
                            </li>
                            <li class="tab col s3">
                                <a href="#tab-location"
                                   class="tooltipped-project-details"
                                   data-tooltip="Location"
                                   data-position="top">
                                    <i class="material-icons" style="font-size:35px;">place</i>
                                </a>
                            </li>
                            <li class="tab col s3">
                                <a href="#tab-files"
                                   class="tooltipped-project-details"
                                   data-tooltip="Files"
                                   data-position="top">
                                    <i class="material-icons" style="font-size:35px;">attach_file</i>
                                </a>
                            </li>
                            <li class="tab col s3">
                                <a href="{{ 'communication__comm_items_panel_html_id'|get_setting }}"
                                   class="tooltipped-project-details"
                                   data-tooltip="Communications"
                                   data-position="top">
                                    <i class="material-icons" style="font-size:35px;">{{ 'communication__comm_items_panel_icon_text'|get_setting }}</i>
                                </a>
                            </li>
                            <li class="tab col s3">
                                <a href="{{ 'communication__disc_items_panel_html_id'|get_setting }}"
                                   class="tooltipped-project-details"
                                   data-tooltip="Discussion"
                                   data-position="top">
                                    <i class="material-icons" style="font-size:35px;">{{ 'communication__disc_items_panel_icon_text'|get_setting }}</i>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div id="tab-main" class="info-panel-height-max">
                        <div class="section">
                            <div class="row">
                                <div class="col s12 m4">
                                    <strong>Project Status:&nbsp;&nbsp;&nbsp;</strong>
                                    {% if object.status == 'active' %}
                                        <span class="badge cedar-badge green white-text">Active</span>
                                    {% else %}
                                        <span class="badge cedar-badge grey darken-3 white-text">Inactive</span>
                                    {% endif %}
                                </div>
                                <div class="hide-on-med-and-up"><br/><br/></div>
                                <div class="col s6 m4">
                                    <strong>Start Date:&nbsp;&nbsp;&nbsp;</strong>
                                    <span class=" grey-text pre">{{ object.start_date| default:"Not specified" }}</span>
                                </div>
                                <div class="col s6 m4">
                                    <strong>End Date:&nbsp;&nbsp;&nbsp;</strong>
                                    <span class=" grey-text pre">{{ object.end_date| default:"Not specified" }}</span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col s12 m6">
                                    <p>
                                        <strong>Author:&nbsp;&nbsp;&nbsp;</strong>
                                        <span class="grey-text lighten-1">
                                            {{ object.author|default:"Not specified" }}
                                        </span>
                                    </p>
                                </div>
                                <div class="col s12 m6">
                                    <p><strong>Contacts</strong></p>
                                    <div class="">
                                        {% for person in object.contacts.all %}
                                            <div class="grey-text lighten-1">
                                                <a href="{% url "crm:person-detail" pk=person.id %}">{{ person }}</a>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col s12">
                                    <p><strong>Project Description</strong></p>
                                    <div class="col">
                                        <span class=" grey-text">{{ object.description|strip_html_wrap }}</span>
                                    </div>
                                </div>
                                {% for key in misc_textarea_fields %}
                                    {% get_dict_val object.misc_textareas key as misc_textarea %}
                                    {% if misc_textarea %}
                                        <div class="row">
                                            <p><strong>{{ key }}</strong></p>
                                            <div class="col">
                                                <span class=" grey-text">{{ misc_textarea|safe }}</span>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div id="tab-location" class="info-panel-height-max">
                        <div class="section">
                            <div id="project-location-map"></div>
                        </div>
                    </div>
                    <div id="tab-files" class="col s12  info-panel-height-max">
                        <div id="assets-table">
                            <table class="highlight">
                                <tbody>
                                <th data-field="name">Filename</th>
                                <th data-field="type">Date Modified</th>
                                <th data-field="type">Size</th>
                                <th data-field="manage">Manage</th>
                                {% for asset in object.ecosystemsprojectasset_set.all %}
                                    <tr>
                                        <td class="extra-tight-table-row"><a href="{% url 'ecosystems:project-secureasset-detail' pk=asset.pk project_pk=object.pk %}">
                                            {{ asset.name }}
                                        </a></td>
                                        <td class="extra-tight-table-row">{{ asset.modified }}</td>
                                        <td class="extra-tight-table-row">{{ asset.file_size_str }}</td>
                                        <td class="extra-tight-table-row">
                                            <a class="waves-grey lighten-5 grey-text text-darken-1 tooltipped-secureasset-delete" href="
                                                {% url 'ecosystems:project-secureasset-delete' project_pk=object.id pk=asset.id %}
                                                " data-tooltip="Delete File" data-position="left">
                                                <i class="material-icons" style="font-size:inherit;">delete</i>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div id="{{ 'communication__comm_items_panel_html_id'|get_setting|slice:"1:" }}" class="col s12  info-panel-height-max">
                        {% render_communication_tools related_object=object element_id='comms_panel' %}
                    </div>
                    <div id="{{ 'communication__disc_items_panel_html_id'|get_setting|slice:"1:" }}" class="col s12  info-panel-height-max">
                        {% render_comment_list for object %}
                        {% render_cedar_comment_form object=object %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">

        var project_info_ajax_url = "{{ project_info_ajax_url }}";
        console.log("project: ", project_info_ajax_url);

    </script>
{% endblock content %}

{% block javascripts %}
    {% react %}
    {% react_dom %}

    {#    <script type="text/javascript" src="{% static 'build/heritage/js/project_detail.js' %}"></script>#}
    {# crm_person_list 'project_person_list' person_info_ajax_url pager=0 search=0 #}

    <script>
        var enable_pagination = false;
    </script>
    <script src='{% static 'lib/DataTables/datatables.js' %}'></script>

    <script>
        var current_nav_url = '{% url 'ecosystems:project-list' %}';

        $(document).ready(function (evt) {
            $('a.tooltipped-secureasset-delete').tooltip();
            $('.tooltipped-project-details').tooltip();
        });
    </script>

    {% leaflet_assets_js %}  {# Load the leaflet assets from the vendor #}
    {% leaflet_load_main %}  {# Load our main leaflet react class #}
    {% leaflet_map_json 'map_default' as map_settings_json %}  {# Load the template map as a starter #}

    {# Pass the template map and ajax url into the leaflet feature map code #}
    {% ecosystems_geoinfo_feature_map attach_id='project-location-map' map_settings=map_settings_json ajax_url=feature_ajax_url ecosystems_project=object %}
    <script>console.log("ajax_url:", "{{feature_ajax_url}}");</script>
{% endblock %}

ecosystems/templates/ecosystems/planttag_confirm_delete.html
{% extends "base.html" %}
{% load cedar_material_form %}
{% load staticfiles %}
{% load cedar_extras %}

{# Uncomment the next line to blankout/override the 2nd bar #}
{#{% block second_bar %}{% endblock %}#}
{% block second_bar_page_title %}Delete Plant{% endblock %}
{% block second_bar_secondary_title %}{{ object.name }} {% endblock %}
{% block second_bar_secondary_content_right %}
    <a class="waves-effect waves-light btn grey lighten-5 grey-text text-darken-2"
       href="{% url 'ecosystems:planttag-detail' object.pk %}">
        <div class="valign-wrapper">
            <i class="material-icons valign ">cancel</i>
            &nbsp;Cancel
        </div>
    </a>
{% endblock %}


{% block content %}
    {{ block.super }}
    <div class="section">
        <div class="row">
            <div class="col s12">
                <form action="{% url 'ecosystems:planttag-delete'  object.pk %}" method="POST">
                    {% csrf_token %}
                    <p>
                        Are you sure you want to delete <strong>{{ object }}</strong>
                    </p>

                    <input class="waves-effect waves-light btn grey lighten-4 red-text text-darken-1" type="submit" value="Confirm delete"/>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    <script>
        var current_nav_url = '{% url "ecosystems:dashboard" %}';
    </script>

{% endblock %}