assets/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from rest_framework import routers

import assets

# api:
from .views import SecureAssetViewSet

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'assets', SecureAssetViewSet, 'secure-assets')

urlpatterns = [

    url(r'^media-secure/download/(?P<file_id>[0-9]+)/$',
        assets.views.GetSecureFileView.as_view(),
        kwargs={'as_attachment': True},
        name='secureasset-download'),
    url(r'^media-secure/serve/(?P<file_id>[0-9]+)/$',
        assets.views.GetSecureFileView.as_view(),
        kwargs={'as_attachment': False},
        name='secureasset-serve'),

    # url(r'^securefile/detail/(?P<pk>[0-9]+)/$', assets.views.SecureAssetDetailView.as_view(), name='secureasset-detail'),
    # url(r'^securefile/edit/(?P<pk>[0-9]+)/$', assets.views.SecureAssetUpdateView.as_view(), name='secureasset-update'),
    # url(r'^securefile/delete/(?P<pk>[0-9]+)/$', assets.views.SecureAssetDeleteView.as_view(), name='secureasset-delete'),
    # url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

    url(r'^file-download/(?P<file_id>[0-9]+)/$',
        assets.views.GetInsecureFileView.as_view(),
        kwargs={'as_attachment': True},
        name='asset-download'),
    url(r'^file/(?P<file_id>[0-9]+)/$',
        assets.views.GetInsecureFileView.as_view(),
        kwargs={'as_attachment': False},
        name='asset-serve'),

    url(r'^file/new/$', assets.views.SecureAssetCreateView.as_view(), name='secureasset-create'),
    url(r'^file/detail/(?P<pk>[0-9]+)/$', assets.views.SecureAssetDetailView.as_view(), name='secureasset-detail'),
    url(r'^file/edit/(?P<pk>[0-9]+)/$', assets.views.SecureAssetUpdateView.as_view(), name='secureasset-update'),
    url(r'^file/delete/(?P<pk>[0-9]+)/$', assets.views.SecureAssetDeleteView.as_view(), name='secureasset-delete'),

    # I don't really like it here. I also wonder if it would be helpful to have a
    # url that takes a setting name as one of the url components.
    url(r'^file/setting/$', assets.views.SetFileSettingView.as_view(), name='asset-setting'),

    url('^dashboard/$', assets.views.SecureAssetsDashboardView.as_view(), name='secureasset-dashboard'),
    url('^search/$', assets.views.SecureAssetSearchView.as_view(), name='secureasset-search'),
    # url('^library/search/$', assets.views.SecureAssetSearchViewCSV.as_view(), name='secureasset-search-csv'),
    url('^list/$', assets.views.SecureAssetListView.as_view(), name='secureasset-list'),

    url('^manage$', assets.views.SecureAssetManageView.as_view(), name='manage'),

    # Wire up our API using automatic URL routing.
    url(r'^api/', include(router.urls, namespace='api')),

]

cedar/urls.py
"""cedar URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/

"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.decorators import login_required

from djcelery.views import is_task_successful, task_status

from . import views
from cedar.forms import CedarPasswordResetForm

from heritage.forms import HeritageAssetForm

urlpatterns = [
    url(r'^$', login_required(views.HomeView.as_view()), name='home'),
    url(r'^spatialtools/', include('geoinfo.urls', namespace='geoinfo')),

    url(r'^heritage/', include('heritage.urls', namespace='heritage')),
    url(r'^heritage/', include('library.urls', namespace='heritage-library', app_name='library'),
        {
            'default_asset_model': 'heritage.heritageasset',
            'default_asset_modelform': HeritageAssetForm}
        ),

    url(r'^development/', include('development.urls', namespace='development')),
    # url(r'^development/', include('library.urls', namespace='development-library', app_name='library')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^assets/', include('assets.urls', namespace='assets')),
    url(r'^help/', include('help.urls', namespace='help')),
    url(r'^communication/', include('communication.urls', namespace='communication')),
    url(r'^eco/', include('ecosystems.urls', namespace='ecosystems')),

    # url(r'^secure/(?P<file_id>[0-9]+)', login_required(assets.views.download_private_file), name='secure'),
    # url(r'^{0}/(?P<file_id>[0-9]+)'.format(settings.SECURE_MEDIA_URL.lstrip('/')), login_required(assets.views.download_private_file), name='secure_handler'),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

    url(r'^crm/', include('crm.urls', namespace="crm")),
    url(r'^maps/', include('maps.urls', namespace="maps")),
    url(r'^communitymap/', include('communitymap.urls', namespace="communitymap")),

    # AUTH and USER SETTINGS:
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': settings.LOGIN_URL}, name='logout'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(
        r'^password/reset/$',
        'django.contrib.auth.views.password_reset',
        name='password_reset',
        kwargs={
            'template_name': 'password_reset_form.html',
            'email_template_name': 'password_reset.txt',
            'html_email_template_name': 'password_reset_email.html',
            'subject_template_name': 'password_reset_subject.txt',
            'password_reset_form': CedarPasswordResetForm
        }
    ),
    url(
        r'^password/reset/done/$',
        'django.contrib.auth.views.password_reset_done',
        name='password_reset_done',
        kwargs={
            'template_name': 'password_reset_done.html'
        }
    ),
    url(
        r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm',
        kwargs={
            'template_name': 'password_reset_confirm.html',
            'post_reset_redirect': 'password_reset_complete'
        }
    ),
    url(
        r'^password/reset/complete/$',
        'django.contrib.auth.views.password_reset_complete',
        name='password_reset_complete',
        kwargs={
            'template_name': 'password_reset_complete.html',
        }
    ),
    url(r'^user-settings/$', login_required(views.UpdateUserSettingsView.as_view()), name='user-settings'),
    url(
        r'^user-settings/change-password$',
        'django.contrib.auth.views.password_change',
        name='change-password',
        kwargs={
            'template_name': 'user_password_change_form.html',
            'post_change_redirect': 'change-password-done',
        }
    ),
    url(
        r'^user-settings/change-password-done$',
        'django.contrib.auth.views.password_change_done',
        name='change-password-done',
        kwargs={'template_name': 'user_password_change_done.html'}
    ),

    # Search - this is the site-wide search. Heritage has it's own.
    # url(r'^search/', login_required(assets.views.SecureAssetSearchView.as_view()), name='search'),

    # Provide a way to access the 404 page outside of DEBUG mode.
    url(r'^404/', views.Cedar404View.as_view(), name='404'),
    # Provide a way to access the 403 page outside of DEBUG mode.
    url(r'^403/', views.Cedar403View.as_view(), name='403'),

    # Additionally, we include login URLs for the browsable API.
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Core celery views to expose webhooks.
    url(r'^celery/apply/(?P<task_name>.*)/$', views.apply_celery_task, name='celery-apply'),
    url(r'^celery/(?P<task_id>[\w\d\-]+)/done/?$', is_task_successful, name='celery-is_task_successful'),
    url(r'^celery/(?P<task_id>[\w\d\-]+)/status/?$', task_status, name='celery-task_status'),
    url(r'^celery/(?P<task_id>[\w\d\-]+)/revoke/?$', views.revoke_celery_task, name='celery-task_revoke'),

    # discussion top-level
    url(r'^comments/', include('django_comments.urls')),

    # Django taggit autosuggest top-level
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^tags/', include('tags.urls', namespace='tags'))
]

# Rename Admin header here:
admin.site.site_header = 'Cedar 8 Administration'

crm/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'role', views.RoleViewSet, 'role')
router.register(r'organization', views.OrganizationViewSet, 'organization')
router.register(r'person', views.PersonViewSet, 'person')

urlpatterns = [
    url(r'^person/list/$', views.PersonListView.as_view(), name='person-list'),
    url(r'^person/(?P<pk>[0-9]+)/$', views.PersonDetailView.as_view(), name='person-detail'),
    url(r'^person/new/$', views.PersonCreateView.as_view(), name='person-create'),
    url(r'^person/(?P<pk>[0-9]+)/update/$', views.PersonUpdateView.as_view(), name='person-update'),
    url(r'^person/(?P<pk>[0-9]+)/delete/$', views.PersonDeleteView.as_view(), name='person-delete'),

    url(r'^organization/list/$', views.OrganizationListView.as_view(), name='organization-list'),
    url(r'^organization/(?P<pk>[0-9]+)/$', views.OrganizationDetailView.as_view(), name='organization-detail'),
    url(r'^organization/(?P<pk>[0-9]+)/update/$', views.OrganizationUpdateView.as_view(), name='organization-update'),
    url(r'^organization/(?P<pk>[0-9]+)/delete/$', views.OrganizationDeleteView.as_view(), name='organization-delete'),
    url(r'^organization/new/$', views.OrganizationCreateView.as_view(), name='organization-create'),

    # Rest API URL routing.
    url(r'^api/', include(router.urls, namespace='api')),
]

assets/forms.py
from django import forms
from haystack.forms import SearchForm
from .models import AssetType, SecureAsset, MetaDocumentAsset, MetaDocumentSecureAsset, Asset
from .search_backend import CustomSearchQuerySet
from cedar_settings.models import GeneralSetting


class AssetForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(AssetForm, self).__init__(*args, **kwargs)
        self.fields['asset_type'].initial = AssetType.objects.get(type_of_asset='Uncategorized')
        self.fields['file'].label = ''

    # override the save and automatically set the name attribute
    # from the file if the file has been changed:
    def save(self, commit=True):
        asset = super(AssetForm, self).save(commit=False)
        if 'file' in self.changed_data:
            name = asset.file.name
            asset.name = name
        asset.save()
        return asset

    class Meta:
        model = Asset
        # exclude = ['delete_file_with_record', 'modified']
        fields = ('file',
                  'comment',
                  'asset_type',
                  # 'name'
                  )


class SecureAssetForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(SecureAssetForm, self).__init__(*args, **kwargs)
        # self.fields['asset_type'].initial = AssetType.objects.get(type_of_asset='Uncategorized')
        self.fields['file'].label = ''

    # override the save and automatically set the name attribute
    # from the file if the file has been changed:
    def save(self, commit=True):
        asset = super(SecureAssetForm, self).save(commit=False)
        if 'file' in self.changed_data:
            name = asset.file.name
            asset.name = name
        asset.save()
        return asset

    class Meta:
        model = SecureAsset
        # exclude = ['delete_file_with_record', 'modified']
        fields = ('file',
                  'comment',
                  'asset_type',
                  # 'name'
                  )


class SecureAssetSearchForm(SearchForm):

    asset_type = forms.ModelMultipleChoiceField(
        queryset=AssetType.objects.all(),
        # widget=forms.CheckboxSelectMultiple
        required=False,
        show_hidden_initial=False,
        widget=forms.SelectMultiple(attrs={'class': 'multiple'}),
        # initial={'asset_type': AssetType.objects.filter(type_of_asset='Transcript').first().id}
        initial={'asset_type': AssetType.objects.values_list('id', flat=True)},
    )

    number_of_excerpt_characters = forms.IntegerField(initial=500, required=True, max_value=51200)

    page = forms.IntegerField(widget=forms.HiddenInput(), initial=1)  # for the paginator

    return_as_csv = forms.CharField(widget=forms.HiddenInput(), initial="no", required=False)

    def __init__(self, *args, **kwargs):

        self.searchqueryset = kwargs.pop('searchqueryset', None)
        self.load_all = kwargs.pop('load_all', False)

        # This conditional was copied out of the source but never resolves True.
        # THe type of SearchQuerySEt was overriden in the View
        # Probably dumpable.
        if self.searchqueryset is None:
            self.searchqueryset = CustomSearchQuerySet()

        kwargs['searchqueryset'] = self.searchqueryset

        super(SecureAssetSearchForm, self).__init__(*args, **kwargs)

    # Keep the below for reference. May be searching by dates at some point:
    def alternate_search(self):
        # First, store the SearchQuerySet received from other processing.
        sqs = super(SecureAssetSearchForm, self).search()

        if not self.is_valid():
            return self.no_query_found()

            # # Check to see if a start_date was chosen.
            # if self.cleaned_data['start_date']:
            #     sqs = sqs.filter(pub_date__gte=self.cleaned_data['start_date'])
            #
            # # Check to see if an end_date was chosen.
            # if self.cleaned_data['end_date']:
            #     sqs = sqs.filter(pub_date__lte=self.cleaned_data['end_date'])

    def search(self):
        if not self.is_valid():
            return self.no_query_found()

        if not self.cleaned_data.get('q'):
            return self.no_query_found()

        asset_types = self.cleaned_data.get('asset_type', None)

        fragmentsize = self.cleaned_data.get('number_of_excerpt_characters', 500)

        # Hardcode max number of snippets here to 100. The backend has set the maximum
        # possible number of characters analyzed to 1 million, so, snippets_num
        # could potentially be bumped up a lot higher, doesn't seem very useful to
        # me though.
        snippets_num = 100

        # The haystack sqs filtering is not adding the asset_type portion of the
        # query properly -> it is no wrapping it in () as it needs to.
        # UPDATE: solr has a weird interpretation of AND/OR precedence.
        # see: http://robotlibrarian.billdueber.com/2011/12/solr-and-boolean-operators/
        # We should seriously consider dropping the AND/OR syntax and using the
        # Google-like EDISMAX query parser.
        # sqs = self.searchqueryset.raw_search(self.cleaned_data['q']) \
        #     .filter(asset_type__in=asset_types) \
        #     .highlight(fragsize=fragmentsize, snippets=snippets_num)


        # Manually wrap the query with parentheses and life goes on....
        sqs = self.searchqueryset.raw_search('({})'.format(self.cleaned_data['q']))

        # set asset types if needed:
        if asset_types:
            sqs = sqs.filter(asset_type__in=asset_types)

        sqs = sqs.highlight(fragsize=fragmentsize, snippets=snippets_num)

        if self.load_all:
            sqs = sqs.load_all()

        return sqs


class MetaDocumentSecureAssetForm(forms.ModelForm):
    class Meta:
        model = MetaDocumentSecureAsset
        fields = '__all__'


class MetaDocumentAssetForm(forms.ModelForm):
    class Meta:
        model = MetaDocumentAsset
        fields = '__all__'


class FileSettingForm(AssetForm):
    setting_choices = (
        ('example', 'choice')
    )
    setting = forms.ChoiceField(choices=setting_choices, required=False, label="Setting Name")

    def __init__(self, *args, **kwargs):
        super(FileSettingForm, self).__init__(*args, **kwargs)
        # self.fields['setting'].choices = GeneralSetting.objects.all().values_list(['name', 'name'])
        self.fields['setting'].choices = [(obj.name, obj.name) for obj in GeneralSetting.objects.all()]

    def save(self, commit=True):
        instance = super(FileSettingForm, self).save(commit=True)

        setting = self.cleaned_data.get('setting', None)
        GeneralSetting.objects.set(
            name=setting,
            value=instance,
            # value = Asset.objects.first(),
            data_type='reference'
        )
        return instance

    class Meta(AssetForm.Meta):
        model = Asset
        fields = AssetForm.Meta.fields + ('setting',)

assets/templates/assets/assets_manage.html
{% extends "base.html" %}
{% load cedar_extras %}
{% load staticfiles %}

{% block stylesheets %}
    {{ block.super }}
    <link href="{% static 'css/task-mon.css' %}" rel="stylesheet"/>
{% endblock %}

{# Uncomment the next line to blankout/override the 2nd bar #}
{#{% block second_bar %}{% endblock %}#}
{% block second_bar_page_title %}Files Management{% endblock %}
{% block second_bar_secondary_title %}{% endblock %}
{% block second_bar_secondary_content_right %} {% endblock %}


{% block content %}
    {{ block.super }}
    <div class="background-image">
        <div class="row">
            <div class="col s12">
                <ul class="collection with-header">
                    <li class="collection-header">
                        <h5>Manage Document Index (note - task not executing yet).</h5>
                    </li>
                    <li class="collection-item">
                        <div>
                            <span data-task-trigger-url="{% url 'celery-apply' task_name='assets.tasks.update_index'%}" >Update document index</span>
                            <span class="secondary-content">
                                <a href="#"
                                   class="tooltipped-management task-trigger"
                                   data-task-id=""
                                   data-task-trigger-url="{% url 'celery-apply' task_name='assets.tasks.update_index'%}"
                                   data-task-status-url-mask="{% url 'celery-task_status' task_id='placeholder' %}"
                                   data-task-revoke-url-mask="{% url 'celery-task_revoke' task_id='placeholder' %}"
                                   data-tooltip="Run indexer"
                                   data-position="left">
                                    <i class="material-icons start-icon">send</i>
                                    <i class="material-icons running-icon">directions_run</i>
                                </a>
                                <a href="#"
                                   class="tooltipped-harvest task-killer red-text"
                                   data-task-id=""
                                   data-tooltip="Stop task"
                                   data-position="top">
                                    <i class="material-icons">close</i>
                                </a>
                            </span>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}


{% block javascripts %}
    {{ block.super }}
    <script src="{% static 'js/task-mon.js' %}"></script>

    <script>
        $(document).ready(function(evt){
            $('.tooltipped-management').tooltip();
        });
    </script>
{% endblock %}

assets/templates/assets/file_table.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/library.css' %}"/>
<script type="text/javascript">

    var table_id = "{{ table_id|escapejs }}";
    var secure_asset_list_ajax_url = "{{ secure_asset_list_ajax_url|escapejs }}";
    var extra_query = "{{ ajax_url_extra_query|escapejs}}"; // This should always be appended to the end of the query url.

</script>
<script type="text/javascript" src="{% static 'bower_components/jquery-typewatch/jquery.typewatch.js' %}"></script>
<script type="text/javascript" src="{% static 'build/assets/js/secureasset_table.js' %}"></script>

assets/templates/assets/genericasset_confirm_delete.html
{% extends "base.html" %}
{% load cedar_material_form %}
{% load staticfiles %}
{% load cedar_extras %}

{# Uncomment the next line to blankout/override the 2nd bar #}
{#{% block second_bar %}{% endblock %}#}
{% block second_bar_page_title %}Delete File {% endblock %}
{% block second_bar_secondary_title %}{{ object.name }} {% endblock %}
{% block second_bar_secondary_content_right %}
    <a class="waves-effect waves-light btn grey lighten-5 grey-text text-darken-2"
       href="{{ cancel_url }}">
        <div class="valign-wrapper">
            <i class="material-icons valign ">cancel</i>
            &nbsp;Cancel
        </div>
    </a>
{% endblock %}


{% block content %}
    {{ block.super }}

    <div class="section">
        <div class="row">
            <div class="col s12">
                <form action="" method="POST">
                    {% csrf_token %}
                    <p>Are you sure you want to delete <strong>{{ object }}</strong></p>
                    <input class="waves-effect waves-light btn grey lighten-4 red-text text-darken-1" type="submit" value="Confirm delete"/>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    <script>
        var current_nav_url = "{{ nav_url }}";
    </script>

{% endblock %}

assets/templates/assets/genericasset_detail.html
{% extends "base.html" %}
{% load cedar_material_form %}
{% load staticfiles %}
{% load cedar_extras %}

{% block stylesheets %}
    {{ block.super }}
{% endblock %}

{# Uncomment the next line to blankout/override the 2nd bar #}
{#{% block second_bar %}{% endblock %}#}
{% block second_bar_page_title %}File Details{% endblock %}
{% block second_bar_secondary_title %}{{ title_text }} {{ object.name }}{% endblock %}
{% block second_bar_secondary_content_right %}
    <a class="waves-effect waves-light btn grey lighten-5 grey-text text-darken-2 {{ user|is_disabled:'development.change_developmentproject' }}"
       {% comment %}
       {# TODO Delete this comment block if there aren't any problems #}
       href="{% url 'assets:secureasset-serve' object.id %}">
       {% endcomment %}
       href="{{ object.serve_url }}">
        <div class="valign-wrapper">
            <i class="material-icons">open_in_browser</i>&nbsp;Open
        </div>
    </a>
    <a class="waves-effect waves-light btn grey lighten-5 grey-text text-darken-2 {{ user|is_disabled:'development.change_developmentproject' }}"
       href="{{ object.download_url }}">
        <div class="valign-wrapper">
            <i class="material-icons">file_download</i>&nbsp;Download
        </div>
    </a>
    <a class="waves-effect waves-light btn grey lighten-5 grey-text text-darken-2 {{ user|is_disabled:'development.change_developmentproject' }}"
        {% if edit_url %}
       href="{{ edit_url }}">
        {% else %}
            href="{% url 'assets:secureasset-update' object.id %}">
       {% endif %}
        <div class="valign-wrapper">
            <i class="material-icons">mode_edit</i>&nbsp;Edit
        </div>
    </a>
    <a class="waves-effect waves-light btn grey lighten-5 red-text text-darken-1 {{ user|is_disabled:'development.add_developmentprojectasset' }}"
        {% if delete_url %}
       href="{{ delete_url }}">
        {% else %}
            href="{% url 'assets:secureasset-delete' object.id %}">
        {% endif %}
        <div class="valign-wrapper">
            <i class="material-icons">delete</i>
        </div>
    </a>
{% endblock %}


{% block content %}
    {{ block.super }}
    {% block additional_content_1 %}{% endblock %}
    <div class="section">
        <div class="row">
            <div class="col s12 m6 l4">
                <div class="col s12 teal-text text-darken-5">
                    Filename:
                    <span class="col s12 grey-text text-lighten">
                        {{ object.name }}
                    </span>
                </div>
                {% if object.asset_type %}
                    <div class="col s12 teal-text text-darken-5">
                        Asset type:
                        <span class="col s12 grey-text text-lighten">
                            {{ object.asset_type }}
                        </span>
                    </div>
                {% endif %}
                {% if object.modified %}
                    <div class="col s12 teal-text text-darken-5">
                        <strong>Date modified:</strong>
                        <span class="col s12 grey-text text-lighten">
                            {{ object.modified }}
                        </span>
                    </div>

                {% endif %}

                {% if object.comment %}
                    <div class="col s12 teal-text text-darken-5">
                        <strong>Comment:</strong>
                        <section class="col s12 grey-text text-lighten" style="margin-top: 0;">
                            {{ object.comment | linebreaks }}
                        </section>
                    </div>

                {% endif %}
            </div>
            <div class="col s12 m6 l8">
                {% if object.meta_document %}
                    <div class="">
                        <h5 class="grey-text text-darken-2">Dublin Core Meta</h5>
                        <div class="divider"></div>
                        {% include 'assets/metadocument_detail_fields.html' with meta=object.meta_document %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    {% block additional_content_2 %}{% endblock %}
{% endblock content %}

{% block javascripts %}
    <script src="{% static 'bower_components/select2/dist/js/select2.min.js' %}"></script>
    <script>
        $(document).ready(function () {
            // Fix select 2 style:
            $('.select2.select2-container').css({
                'width': 'inherit'
            });
        });
    </script>
{% endblock %}

assets/templates/assets/genericasset_form.html
{% extends "base.html" %}
{% load cedar_material_form %}
{% load staticfiles %}
{% load cedar_extras %}
{% load assets %}


{# Uncomment the next line to blankout/override the 2nd bar #}
{#{% block second_bar %}{% endblock %}#}
{% block second_bar_page_title %}
    {% is_update_view "Update" "New" as title_text %}
    {{ title_text }} File{% endblock %}
{% block second_bar_secondary_title %}{{ object.name }} {% endblock %}
{% block second_bar_secondary_content_right %}{% endblock %}


{% block content %}
    {{ block.super }}
    <div class="section">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% block form_fields %}
                {% include 'assets/secureasset_form_fields.html' with form=form %}
            {% endblock %}
        </form>
    </div>
{% endblock content %}

assets/templates/assets/genericassetfilesetting_form.html
{% extends 'assets/genericasset_form.html' %}
{% load cedar_material_form %}


{% block form_fields %}
    <div class="row">
        <div class="col s8">
            {{ form.setting|materialselect2 }}
        </div>
    </div>
    {{ block.super }}


    <script>
        $(document).ready(function(e){
            {% if hide_meta_doc %}
                $('div.meta-doc-form-area').css('display', 'none');
            {% endif %}
        });
    </script>
{% endblock form_fields %}

assets/templates/assets/metadocument_empty_form.html
{#Requires the form context varible: "metadocument_formset"#}
{% load cedar_material_form %}
{% load staticfiles %}
{% load cedar_extras %}

<div id="metadocument_formset_empty_form" style="display: none;">
    <div class="metadocument-item item-__prefix__ grey lighten-4 col s12" style="display: none;">
{#        {{ metadocument_formset.empty_form.contributor|materializecss:"s12 m6 l6" }}#}
{#        {{ metadocument_formset.empty_form.coverage|materializecss:"s12 m6 l6" }}#}
{#        {{ metadocument_formset.empty_form.creator|materializecss:"s12" }}#}

        {%  for field in metadocument_formset.empty_form.fields %}
            {{ field|materializecss:"s12" }}
        {% endfor %}

        {% for hidden in metadocument_formset.empty_form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% is_update_view 1 0 as update_view %}
        {% if update_view %}
            <div class="row">
                {{ metadocument_formset.empty_form.DELETE|materializecss }}
            </div>
        {% endif %}
    </div>
</div>

assets/templates/assets/secureasset_list.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load cedar_extras %}
{% load cedar_list %}

{% block stylesheets %}
    <link href="{% static 'css/griddle_style.css' %}" rel="stylesheet"/>
{% endblock %}

{% block second_bar_page_title %}File Browser{% endblock %}
{% block second_bar_secondary_title %}Total Number of Files: <span class="library-file-table-count">{{ total_files }}</span> {% endblock %}
{% block second_bar_secondary_content_right %}
    <a class="waves-effect waves-light btn grey lighten-5 grey-text text-darken-2 {{ user|is_disabled:'assets.add_secureasset' }}"
       href="{% url 'assets:secureasset-create'%}">
        <div class="valign-wrapper">
            <i class="material-icons">add_circle</i>
            &nbsp;File
        </div>
    </a>
{% endblock %}

{% block content %}
    {{ block.super }}
    <div class="row">
        <div class="col s12">
            {# Need to add the div manually.  The include tag is for adding the javascript. #}
            <div id="library-file-table"></div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {% react %}
    {% react_dom %}
    {% cedar_list 'library-file-table' ajax_url=secure_asset_list_ajax_url fields=fields sort_field_options=sort_options default_sort='-id' %}
{% endblock %}