cedar/urls.py
"""cedar URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/

"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.decorators import login_required

from djcelery.views import is_task_successful, task_status

from . import views
from cedar.forms import CedarPasswordResetForm

from heritage.forms import HeritageAssetForm

urlpatterns = [
    url(r'^$', login_required(views.HomeView.as_view()), name='home'),
    url(r'^spatialtools/', include('geoinfo.urls', namespace='geoinfo')),

    url(r'^heritage/', include('heritage.urls', namespace='heritage')),
    url(r'^heritage/', include('library.urls', namespace='heritage-library', app_name='library'),
        {
            'default_asset_model': 'heritage.heritageasset',
            'default_asset_modelform': HeritageAssetForm}
        ),

    url(r'^development/', include('development.urls', namespace='development')),
    # url(r'^development/', include('library.urls', namespace='development-library', app_name='library')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^assets/', include('assets.urls', namespace='assets')),
    url(r'^help/', include('help.urls', namespace='help')),
    url(r'^communication/', include('communication.urls', namespace='communication')),
    url(r'^eco/', include('ecosystems.urls', namespace='ecosystems')),

    # url(r'^secure/(?P<file_id>[0-9]+)', login_required(assets.views.download_private_file), name='secure'),
    # url(r'^{0}/(?P<file_id>[0-9]+)'.format(settings.SECURE_MEDIA_URL.lstrip('/')), login_required(assets.views.download_private_file), name='secure_handler'),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

    url(r'^crm/', include('crm.urls', namespace="crm")),
    url(r'^maps/', include('maps.urls', namespace="maps")),
    url(r'^communitymap/', include('communitymap.urls', namespace="communitymap")),

    # AUTH and USER SETTINGS:
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': settings.LOGIN_URL}, name='logout'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(
        r'^password/reset/$',
        'django.contrib.auth.views.password_reset',
        name='password_reset',
        kwargs={
            'template_name': 'password_reset_form.html',
            'email_template_name': 'password_reset.txt',
            'html_email_template_name': 'password_reset_email.html',
            'subject_template_name': 'password_reset_subject.txt',
            'password_reset_form': CedarPasswordResetForm
        }
    ),
    url(
        r'^password/reset/done/$',
        'django.contrib.auth.views.password_reset_done',
        name='password_reset_done',
        kwargs={
            'template_name': 'password_reset_done.html'
        }
    ),
    url(
        r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm',
        kwargs={
            'template_name': 'password_reset_confirm.html',
            'post_reset_redirect': 'password_reset_complete'
        }
    ),
    url(
        r'^password/reset/complete/$',
        'django.contrib.auth.views.password_reset_complete',
        name='password_reset_complete',
        kwargs={
            'template_name': 'password_reset_complete.html',
        }
    ),
    url(r'^user-settings/$', login_required(views.UpdateUserSettingsView.as_view()), name='user-settings'),
    url(
        r'^user-settings/change-password$',
        'django.contrib.auth.views.password_change',
        name='change-password',
        kwargs={
            'template_name': 'user_password_change_form.html',
            'post_change_redirect': 'change-password-done',
        }
    ),
    url(
        r'^user-settings/change-password-done$',
        'django.contrib.auth.views.password_change_done',
        name='change-password-done',
        kwargs={'template_name': 'user_password_change_done.html'}
    ),

    # Search - this is the site-wide search. Heritage has it's own.
    # url(r'^search/', login_required(assets.views.SecureAssetSearchView.as_view()), name='search'),

    # Provide a way to access the 404 page outside of DEBUG mode.
    url(r'^404/', views.Cedar404View.as_view(), name='404'),
    # Provide a way to access the 403 page outside of DEBUG mode.
    url(r'^403/', views.Cedar403View.as_view(), name='403'),

    # Additionally, we include login URLs for the browsable API.
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Core celery views to expose webhooks.
    url(r'^celery/apply/(?P<task_name>.*)/$', views.apply_celery_task, name='celery-apply'),
    url(r'^celery/(?P<task_id>[\w\d\-]+)/done/?$', is_task_successful, name='celery-is_task_successful'),
    url(r'^celery/(?P<task_id>[\w\d\-]+)/status/?$', task_status, name='celery-task_status'),
    url(r'^celery/(?P<task_id>[\w\d\-]+)/revoke/?$', views.revoke_celery_task, name='celery-task_revoke'),

    # discussion top-level
    url(r'^comments/', include('django_comments.urls')),

    # Django taggit autosuggest top-level
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^tags/', include('tags.urls', namespace='tags'))
]

# Rename Admin header here:
admin.site.site_header = 'Cedar 8 Administration'

crm/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'role', views.RoleViewSet, 'role')
router.register(r'organization', views.OrganizationViewSet, 'organization')
router.register(r'person', views.PersonViewSet, 'person')

urlpatterns = [
    url(r'^person/list/$', views.PersonListView.as_view(), name='person-list'),
    url(r'^person/(?P<pk>[0-9]+)/$', views.PersonDetailView.as_view(), name='person-detail'),
    url(r'^person/new/$', views.PersonCreateView.as_view(), name='person-create'),
    url(r'^person/(?P<pk>[0-9]+)/update/$', views.PersonUpdateView.as_view(), name='person-update'),
    url(r'^person/(?P<pk>[0-9]+)/delete/$', views.PersonDeleteView.as_view(), name='person-delete'),

    url(r'^organization/list/$', views.OrganizationListView.as_view(), name='organization-list'),
    url(r'^organization/(?P<pk>[0-9]+)/$', views.OrganizationDetailView.as_view(), name='organization-detail'),
    url(r'^organization/(?P<pk>[0-9]+)/update/$', views.OrganizationUpdateView.as_view(), name='organization-update'),
    url(r'^organization/(?P<pk>[0-9]+)/delete/$', views.OrganizationDeleteView.as_view(), name='organization-delete'),
    url(r'^organization/new/$', views.OrganizationCreateView.as_view(), name='organization-create'),

    # Rest API URL routing.
    url(r'^api/', include(router.urls, namespace='api')),
]

geoinfo/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'layer', views.GISLayerViewSet, 'layer')
router.register(r'feature', views.GISFeatureViewSet, 'feature')
router.register(r'spatialreport', views.SpatialReportViewSet, 'spatialreport')

urlpatterns = [
    url(r'^$', views.DashboardView.as_view(), name='dashboard'),

    # Layer views
    url(r'^layer/misc/(list/)?$', views.GISLayerListView.as_view(), name='layer-list'),
    url(r'^layer/all/(list/)?$', views.GISLayerMasterListView.as_view(), name='layer-master-list'),
    url(r'^layer/(?P<pk>[0-9]+)/$', views.GISLayerDetailView.as_view(), name='layer-detail'),
    url(r'^feature/(?P<pk>[0-9]+)/$', views.GISFeatureDetailView.as_view(), name='feature-detail'),
    url(r'^layer/new/', views.GISLayerCreateView.as_view(), name='layer-create'),
    url(r'^layer/(?P<pk>[0-9]+)/update/$', views.GISLayerUpdateView.as_view(), name='layer-update'),
    url(r'^layer/(?P<pk>[0-9]+)/delete/$', views.GISLayerDeleteView.as_view(), name='layer-delete'),

    # Spatial report views
    url(r'^spatialreport/(list/)?$', views.SpatialReportListView.as_view(), name='spatialreport-list'),
    url(r'^spatialreport/(?P<pk>[0-9]+)/$', views.SpatialReportDetailView.as_view(), name='spatialreport-detail'),
    url(r'^spatialreport/new/$', views.SpatialReportCreateView.as_view(), name='spatialreport-create'),
    url(r'^spatialreport/(?P<pk>[0-9]+)/update/$',
        views.SpatialReportUpdateView.as_view(), name='spatialreport-update'),
    url(r'^spatialreport/(?P<pk>[0-9]+)/delete/$',
        views.SpatialReportDeleteView.as_view(), name='spatialreport-delete'),

    # Spatial report item views
    url(r'^spatialreport/(?P<report_pk>[0-9]+)/item/new/$',
        views.SpatialReportItemCreateView.as_view(), name='spatialreportitem-create'),
    url(r'^spatialreport/(?P<report_pk>[0-9]+)/item/(?P<pk>[0-9]+)/update/$',
        views.SpatialReportItemUpdateView.as_view(), name='spatialreportitem-update'),
    url(r'^spatialreportitem/(?P<pk>[0-9]+)/delete/$',
        views.SpatialReportItemDeleteView.as_view(), name='spatialreportitem-delete'),

    # Rest API URL routing.
    url(r'^api/', include(router.urls, namespace='api')),
    url(r'^api/layer-master/$', views.GISLayerMasterListAPIView.as_view(), name='layer-master-list-api'),
    url(r'^api/feature-point/$', views.GISFeaturePointViewSet.as_view(), name='feature-point-list'),
    url(r'^api/feature-line/$', views.GISFeatureLineViewSet.as_view(), name='feature-line-list'),
    url(r'^api/feature-polygon/$', views.GISFeaturePolygonViewSet.as_view(), name='feature-polygon-list'),
]

geoinfo/templates/geoinfo/gisfeature_detail.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load cedar_extras %}
{% load html_filters %}
{% load leaflet_assets %}
{% load geoinfo %}

{% block stylesheets %}
    {{ block.super }}

    {% leaflet_assets_css %}
{% endblock %}

{# Note: {{ block.super }} must appear in the {% block content %} tag for the following to work. #}
{# Note: uncomment the next line to blankout/override the 2nd bar #}
{#{% block second_bar %}{% endblock %}#}
{% block second_bar_page_title %}{{ gisfeature }}{% endblock %}
{% block second_bar_secondary_title %}Layer: <a href="{% url 'geoinfo:layer-detail' gisfeature.layer.id %}">{{ gisfeature.layer }}</a>{% endblock %}
{% block second_bar_secondary_content_right %} {% endblock %}

{% block content %}
    {{ block.super }}

    <div class="row">
        <div class="col s12 m6 l4">
            <h4>Attributes</h4>
            {% for label, value in gisfeature.data.items %}
                <div class="row tight-row">
                    <div class="col s6 grey-text text-darken-4">{{ label }}:</div>
                    <div class="col s6 grey-text text-darken-1">{{ value|strip_html_wrap }}</div>
                </div>
            {% endfor %}
        </div>
        <div class="col s12 m6 l8">
            <div id="feature-map"></div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ block.super }}

    <script>
        var current_nav_url = '{% url "geoinfo:layer-list" %}';
    </script>

    {% react %}
    {% react_dom %}
    {% leaflet_assets_js %}
    {% leaflet_load_main %}
    {% leaflet_map_json 'map_default' as map_json %}
    {% geoinfo_feature_map 'feature-map' map_json feature_ajax_geojson_url %}
{% endblock %}

geoinfo/templates/geoinfo/gisfeature_list_include.html
{% load staticfiles %}

<script type="text/javascript">
    var geoinfo_feature_list_attach_id = "{{ attach_id|escapejs }}";
    var geoinfo_feature_list_ajax_url = "{{ ajax_url|escapejs }}";
    var geoinfo_feature_list_show_pager = {{ pager|escapejs }};
    var geoinfo_feature_list_show_search = {{ search|escapejs }};
</script>
<script type="text/javascript" src="{% static 'build/geoinfo/js/feature_list_component.js' %}"></script>
<script type="text/javascript" src="{% static 'build/geoinfo/js/feature_list.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/cedar-react-list.css' %}">

geoinfo/templates/geoinfo/gislayer_detail.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load cedar_extras %}
{% load html_filters %}
{% load leaflet_assets %}
{% load geoinfo %}

{% block stylesheets %}
    {{ block.super }}

    {% leaflet_assets_css %}
{% endblock %}

{# Note: {{ block.super }} must appear in the {% block content %} tag for the following to work. #}
{# Note: uncomment the next line to blankout/override the 2nd bar #}
{#{% block second_bar %}{% endblock %}#}
{% block second_bar_page_title %}{{ object }}{% endblock %}
{% block second_bar_secondary_title %}
{% if object.input_type == 'file' %}
    {{ object.input_type }} - {{ object.file.name }}
{% else %}
    {{ object.input_type }}
{% endif %}
{% endblock %}
{% block second_bar_secondary_content_right %}
    <a class="waves-effect waves-light btn grey lighten-5 grey-text text-darken-2 {{ user|is_disabled:'geoinfo.change_gislayer' }}"
       {% if object.get_edit_url %}
           href="{{ object.get_edit_url }}"
       {% else %}
           href="{% url 'geoinfo:layer-update'  object.id %}"
       {% endif %}
    >
        <div class="valign-wrapper">
            <i class="material-icons valign ">edit</i>
            &nbsp;Edit
        </div>
    </a>
    &nbsp;

{% endblock %}

{% block content %}
    {{ block.super }}

    <section>
        <div class="row">
            <div class="col s12 m4 l4">
                <p>{{ object.notes|strip_html_wrap }}</p>
            </div>

            <div class="col s12 m8 l8 thin-border-left-grey">
                <ul class="tabs hide-scroll-x">
                    <li class="tab col s6"><a class="active" href="#tab-map">Map</a></li>
                    <li class="tab col s6"><a class="active" href="#tab-list">List</a></li>
                </ul>
                <div id="tab-map" class="info-panel-height-max">
                    <div id="feature-map"></div>
                </div>

                <div id="tab-list" class="info-panel-height-max">
                    <div id="feature-list"></div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block javascripts %}
    {{ block.super }}

    <script>
        {% if nav_url %}
            var current_nav_url = '{{ nav_url|safe }}';
        {% else %}
            var current_nav_url = '{% url "geoinfo:layer-master-list" %}';
        {% endif %}
    </script>

    {% react %}
    {% react_dom %}

    {% leaflet_assets_js %}
    {% leaflet_load_main %}
    {% leaflet_map_json 'map_default' as map_json %}
    {% geoinfo_feature_map 'feature-map' map_json feature_ajax_geojson_url %}

    {% geoinfo_feature_list 'feature-list' feature_ajax_url %}
{% endblock %}

geoinfo/templates/geoinfo/gislayer_form.html
{% extends "base.html" %}
{% load cedar_material_form %}
{% load staticfiles %}
{% load cedar_extras %}

{# Uncomment the next line to blankout/override the 2nd bar #}
{#{% block second_bar %}{% endblock %}#}
{% block second_bar_page_title %}
    {% is_update_view "Update" "New" as title_text %}
    {{ title_text }} Spatial Layer
{% endblock %}
{% block second_bar_secondary_title %}{{ object.name }} {% endblock %}
{% block second_bar_secondary_content_right %}{% endblock %}

{% block content %}
    {{ block.super }}
    {% is_update_view "Update" "New" as button_text %}

    <div class="section">
        <div class="row">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div style="display:none;">
                    {{ form.errors }}
                </div>
                {% include 'geoinfo/gislayer_form_fields.html' with form=form %}

                <div class="col s12">
                    <input id="submit-layer"
                            class="waves-effect waves-light btn grey lighten-4 grey-text text-darken-1" type="submit"
                           value="{{ button_text }} Layer"/>

                    {% if object %}
                        <a class="right waves-effect waves-light btn grey lighten-5 red-text text-darken-1 {{ user|is_disabled:'geoinfo.delete_gislayer' }}"
                           href="
                            {% if object.get_delete_url %}
                                {{ object.get_delete_url }}
                            {% else %}
                                {% url 'geoinfo:layer-delete'  gislayer.id %}
                            {% endif %}">
                            <div class="valign-wrapper">
                                <i class="material-icons valign ">delete</i>
                                &nbsp;Delete Layer
                            </div>
                        </a>&nbsp;&nbsp;
                    {% endif %}
                    <div class="preloader-wrapper small active">
                        <div class="spinner-layer spinner-green-only">
                            <div class="circle-clipper left">
                                <div class="circle"></div>
                            </div>
                            <div class="gap-patch">
                                <div class="circle"></div>
                            </div>
                            <div class="circle-clipper right">
                                <div class="circle"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    <script>
        var submit_spinner = $('.preloader-wrapper')
        {% if nav_url %}
            var current_nav_url = '{{ nav_url|safe }}';
        {% else %}
            var current_nav_url = '{% url "geoinfo:layer-list" %}';
        {% endif %}
        submit_spinner.css('visibility', 'hidden');

        $('#submit-layer').click(function(e) {
            submit_spinner.css('visibility', 'visible');
        });
    </script>

{% endblock %}

geoinfo/templates/geoinfo/gislayer_form_fields.html
{% load cedar_material_form %}
{% load staticfiles %}
{% load cedar_extras %}

{# gislayer_form_fields.html  has space #}
{# for subclassed GISLayer classes' templates to add form variables.#}

{#override additional_form_fields_1#}
{#and  additional_form_fields_2#}
{#to add more from fields in subclassed templates.#}

{#When included into a parent template, this form template requires#}
{#submitting the "form" variable.#}

{# this template should be included within <form> tags and doesn't include the submit button #}
{#    so that sub-template extender can define that text as they see fit.#}

{{ form.media }}
{#<div class="row tight-row">#}
{#    {{ form.errors }}#}
{#</div>#}
<div class="row tight-row">
    {{ form.name|materializecss:"s12" }}
</div>
<div class="row"></div>

{#  EG this is used by devt app to add the project name to the form #}
{% block additional_form_fields_1 %} {% endblock %}

<div class="row">
{#    <div class="input-field col s12">#}
{#        <select name="{{ form.input_type.name }} " id="{{ form.input_type.auto_id }}">#}
{#            {% for choice in form.input_type.field.choices %}#}
{#                <option {{ choice|is_choice_selected:form.input_type.value }} value="{{ choice.0 }}">{{ choice.1 }}</option>#}
{#            {% endfor %}#}
{#        </select>#}
{#        <label>{{ form.input_type.label }}</label>#}
{#    </div>#}
    {{ form.input_type | materializecss }}
</div>
<div class="row">
    <div id="outer">
        <div id="feature_titles_template" class="col s12" style="display: none; margin-bottom: 3rem;">
            {{ form.feature_titles_template|materializecss }}
        </div>

        <div id="wkt" class="col s12" style="display:none;">
            {{ form.wkt|materializecss }}
        </div>
        <div id="draw" class="col s12">
            {{ form.draw|materializecss }}
        </div>
        <div id="file" class="col s12" style="display:none;">
            {{ form.file|materializecss }}
        </div>
        <div id="geomark" class="col s12">
            {{ form.geomark|materializecss }}
        </div>
        <div id="wfs" class="col s12">
            {{ form.wfs_geojson|materializecss }}
            {{ form.wfs_username|materializecss }}
            {{ form.wfs_password|materializecss }}
            {{ form.refresh_interval|materializecss }}

            {{ form.polyline_style.as_hidden }}
            {{ form.polygon_style.as_hidden }}
            {{ form.point_style.as_hidden }}
        </div>
    </div>
</div>
<div class="row">
    <div class="col s12">
        {{ form.reload_features|materializecss }}
    </div>
    <div class="row"></div>
    <div class="col s12">
        {{ form.notes|materializecss }}
    </div>
</div>

<script>
    // add listeners that handle showing/hiding stuff

    var div_id_dict = {
        'wkt': '#wkt',
        'file': '#file',
        'map': '#draw',
        'geomark': '#geomark',
        'wfs': '#wfs'
    };


    //Listen for changes to the original select control. These
    // trigger materializecss to do it's thing to it's UI elements
    // sitting on top:
    $("#{{ form.input_type.auto_id }}").on('change', function () {

        //Get selected value from dropdown:
        var input_type_value = $(this).find('option:selected').attr('value');

        //Hide the other showing divs (there really should only be one):
        for (var div_id_key in div_id_dict) {
            // Check we are only going to hide a div that is not of interest:
            var input_div = $(div_id_dict[div_id_key]);
            if (input_type_value != div_id_key) {
                if ($(input_div).is(":visible")) {
                    $(input_div).slideToggle();
                }
            }
            else {
                if (!$(input_div).is(":visible")) {
                    $(input_div).slideToggle();
                }
            }
        }

        // This is hacky... but we want to show the feature title tempalte field for both files and wfs
        var feature_title_template = $('#feature_titles_template');

        if ($.inArray(input_type_value, ["file", "wfs"]) !== -1) {
            if (!feature_title_template.is(":visible")) {
                feature_title_template.slideToggle();
            }
        } else {
            if (feature_title_template.is(":visible")) {
                feature_title_template.slideToggle();
            }
        }

        //Now show the div we want:
        //if it's the map we have to trigger a resize because it
        // may have gotten messed up by initially loading while hidden:
        // NOTE: THIS DIDN"T HELP.
        {#        if (input_type_value == 'map') {#}
        {#            $(div_id_dict[input_type_value]).slideToggle().trigger('resize');#}
        {#        }#}
        {#        else {#}
        {#            $(div_id_dict[input_type_value]).slideToggle()#}
        {#        }#}


    });

    $(document).ready(function () {
        //Trigger the change function on the select to hide controls that we don't want to see:
        $("#{{ form.input_type.auto_id }}").trigger('change');

        //Fudge the map z-index back into place.
        $("#id_draw_div_map").css('z-index', 1);

        //Remove the *highly* irritation float left on the map:
        $("#id_draw_div_map").css('float', 'none');

    });
</script>


{% block additional_form_fields_2 %} {% endblock %}

geoinfo/templates/geoinfo/gislayer_list.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load cedar_extras %}
{% load geoinfo %}

{# Note: {{ block.super }} must appear in the {% block content %} tag for the following to work. #}
{# Note: uncomment the next line to blankout/override the 2nd bar #}
{#{% block second_bar %}{% endblock %}#}
{% block second_bar_page_title %}Misc. Spatial Layers{% endblock %}
{% block second_bar_secondary_title %}<span class="layer-list-count">{{ object_list.count }}</span> Layer{{ object_list|pluralize }} {% endblock %}
{% block second_bar_secondary_content_right %}
    <a class="waves-effect waves-light btn grey lighten-5 grey-text text-darken-2 {{ user|is_disabled:'geoinfo.add_gislayer' }}"
       href="{% url 'geoinfo:layer-create' %}">
        <div class="valign-wrapper">
            <i class="material-icons valign ">add_circle</i>
            &nbsp;Misc. Layer
        </div>
    </a>
{% endblock %}

{% block content %}
    {{ block.super }}

    <div class="row">
        <div id="layer-list" class="col s12"></div>
    </div>
{% endblock %}

{% block javascripts %}
    {% geoinfo_layer_list 'layer-list' ajax_url=ajax_url %}
{% endblock %}

geoinfo/templates/geoinfo/gislayer_list_include.html
{% load staticfiles %}

<script type="text/javascript">
    var geoinfo_layer_list_attach_id = "{{ attach_id|escapejs }}";
    var geoinfo_layer_list_ajax_url = "{{ ajax_url|escapejs }}";
    var geoinfo_layer_list_show_pager = "{{ pager|escapejs }}";
    var geoinfo_layer_list_show_search = "{{ search|escapejs }}";
    var geoinfo_layer_types = {{ layer_type_choices|safe }};
    var geoinfo_layer_list_default_layer_type = "{{ default_layer_type|escapejs }}";
</script>
<link rel="stylesheet" type="text/css" href="{% static 'css/cedar-react-list.css' %}">
<script type="text/javascript" src="{% static 'bower_components/jquery-typewatch/jquery.typewatch.js' %}"></script>
<script type="text/javascript" src="{% static 'build/geoinfo/js/layer_list.js' %}"></script>

geoinfo/templates/geoinfo/gislayer_stats.html
{% if point_count %}<div class="chip">{{ point_count }} point{{ point_count|pluralize }}</div>{% endif %}
{% if line_count %}<div class="chip">{{ line_count }} line{{ line_count|pluralize }}</div>{% endif %}
{% if polygon_count %}
    <div class="chip">
        {{ polygon_count }} polygon{{ polygon_count|pluralize }}
        with a{% if polygon_count > 1 %} combined{% else %}n{% endif %} area of
        {{ polygon_area }} {{ polygon_area_units|safe }}
    </div>
{% endif %}

geoinfo/templates/geoinfo/gislayermaster_list.html
{% extends 'geoinfo/gislayer_list.html' %}
{% load geoinfo %}

{% block second_bar_page_title %}All Spatial Layers{% endblock %}

{% block javascripts %}
    {% geoinfo_layer_list 'layer-list' ajax_url=ajax_url layer_type_choices=layer_type_choices default_layer_type=default_layer_type %}
{% endblock %}

geoinfo/templates/geoinfo/spatialreport_confirm_delete.html
{% extends "base.html" %}
{% load cedar_material_form %}
{% load staticfiles %}
{% load cedar_extras %}

{# Uncomment the next line to blankout/override the 2nd bar #}
{#{% block second_bar %}{% endblock %}#}
{% block second_bar_page_title %}Delete Spatial Report{% endblock %}
{% block second_bar_secondary_title %}{{ spatialreport.name }} {% endblock %}
{% block second_bar_secondary_content_right %}
    <a class="waves-effect waves-light btn grey lighten-5 grey-text text-darken-2"
       href="{% url 'geoinfo:spatialreport-detail' spatialreport.id %}">
        <div class="valign-wrapper">
            <i class="material-icons valign ">cancel</i>
            &nbsp;Cancel
        </div>
    </a>
{% endblock %}


{% block content %}
    {{ block.super }}

    <div class="section">
        <div class="row">
            <div class="col s12">
                <form action="{% url 'geoinfo:spatialreport-delete'  spatialreport.id %}" method="POST">
                    {% csrf_token %}
                    <p>Are you sure you want to delete <strong>{{ spatialreport }}</strong> along with its
                        {{ spatialreport.spatialreportitem_set.count }}
                        item{{ spatialreport.spatialreportitem_set.count|pluralize }}?</p>
                    <input class="waves-effect waves-light btn grey lighten-4 red-text text-darken-1" type="submit" value="Confirm delete"/>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    <script>
        var current_nav_url = '{% url "geoinfo:spatialreport-list" %}';
    </script>

{% endblock %}